Repository mattermost/mattermost-developer-documentation, pull requests merged in 2018-10, with the labels that each got.

#162 Add Explanation for 404 and reference to Webapp Setup
  site/content/contribute/server/developer-setup.md
Labels: 3: Ready to Merge

#171 Fixing typo in redux migration guide (fron --> from)
  site/content/contribute/webapp/webapp-to-redux.md
Labels: 3: Ready to Merge

#168 MM-11423/MM-10578 Add guidance on plugins in HA
  site/content/extend/plugins/server/ha.md
Labels: 3: Ready to Merge

#169 Update building the mobile app
  site/content/contribute/mobile/build-your-own.md
  site/content/contribute/mobile/makefile.md
Labels: 3: Ready to Merge

#173 Fix crash when running plugin-jsdocs.js
  scripts/plugin-jsdocs.js
Labels: 3: Ready to Merge

#170 Update link for interactive messages
  site/content/integrate/getting-started/how-should-i-integrate.md
Labels: Ready to Merge

#175 MM-11709 Add overview to plugins plus other minor updates
  site/content/contribute/server/plugins.md
  site/content/extend/plugins/_index.md
  site/content/extend/plugins/overview/_index.md
  site/content/extend/plugins/server/hello-world.md
  site/content/extend/plugins/webapp/hello-world.md
Labels: PM Review

#177 MM-8374 - Updating docs styling
  site/layouts/blog/list.html
  site/layouts/blog/single.html
  site/layouts/blog/summary.html
  site/layouts/indexes/category.html
  site/layouts/partials/intro.html
  site/static/css/styles.css
Labels: Ready to Merge

#178 blog: idiomatic error handling
  site/content/blog/idiomatic-error-handling.md
  site/static/css/styles.css
Labels: Ready to Merge
