Repository mattermost/mattermost-developer-documentation, pull requests merged in 2018-12, with the labels that each got.

#195 Reduce size of hanchors
  site/static/css/styles.css
Labels: Ready to Merge

#198 Change pre-release for community
  site/content/contribute/getting-started/_index.md
Labels: Dev Review, content

#201 Remove run-fullmap target
  site/content/contribute/server/developer-workflow.md
Labels: Dev Review

#194 Improve Notification Bar
  site/layouts/partials/nav.html
  site/layouts/partials/notification.html
  site/static/css/bar.css
  site/static/css/styles.css
  site/static/js/main.js
Labels: PM Review

#202 Fix doc according to PR-2169
  site/content/contribute/mobile/build-your-own.md
Labels: Ready to Merge

#203 Update Editorconfig
  .editorconfig
Labels: Ready to Merge

#204 Docs for multiple responses from a slash command
  site/content/integrate/slash-commands/_index.md
Labels: Ready to Merge

#206 Add note on supported versions for extra_responses parameter in slash commands
  site/content/integrate/slash-commands/_index.md
Labels: Ready to Merge

#207 document making GitHub membership organization public
  site/content/internal/contributor.png
  site/content/internal/member.png
  site/content/internal/onboarding.md
Labels: Dev Review

#190 [MM-9937] [MM-9938] slash command response parameters update
  site/content/integrate/slash-commands/_index.md
Labels: Ready to Merge

#189 Process for inactive contributions
  site/content/contribute/getting-started/inactive-contribution.md
Labels: Dev Review

#209 Change inactive contributions lifecycle to stale>inactive>orphaned
  site/content/contribute/getting-started/inactive-contributions.md
Labels: Ready to Merge

#196 [MM-13028] Add E2E documentation for Cypress
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/webapp/end-to-end-tests.md
Labels: content

#161 Document out of memory error in running mobile app
  site/content/contribute/mobile/developer-setup.md
Labels: Ready to Merge
