Repository mattermost/mattermost-developer-documentation, pull requests merged in 2018-11, with the labels that each got.

#181 Update mobile node working versions
  site/content/contribute/mobile/developer-setup.md
Labels: Dev Review

#182 [MM-12340] update release process
  site/content/internal/release-process.md
Labels: Ready to Merge

#186 Add new core committers
  site/content/contribute/getting-started/core-committers.md
Labels: Ready to Merge

#184 Add k8s documentation
  site/content/internal/infrastructure/_index.md
  site/content/internal/infrastructure/aws.md
  site/content/internal/infrastructure/build.md
  site/content/internal/infrastructure/kubernetes/_index.md
  site/content/internal/infrastructure/kubernetes/kubernetes.md
  site/content/internal/infrastructure/vault.md
  site/content/internal/infrastructure/vpn.md
  site/content/internal/offboarding.md
  site/content/internal/onboarding.md
  site/content/internal/qa/_index.md
  site/content/internal/release-process.md
  site/content/internal/tips-and-best-practices.md
Labels: Dev Review

#188 Add troubleshooting note for cocoapods error
  site/content/contribute/mobile/developer-setup.md
Labels: Dev Review

#193 Add heading anchor
  site/layouts/_default/list.html
  site/layouts/_default/single.html
  site/layouts/blog/single.html
  site/layouts/partials/hanchor.html
  site/static/css/styles.css
Labels: Ready to Merge

#192 Add edit link to pages
  site/config.toml
  site/layouts/_default/list.html
  site/layouts/_default/single.html
  site/layouts/partials/hanchor.html
  site/layouts/partials/page-edit.html
Labels: Ready to Merge

#191 [MM-12970] Update webapp unit-testing and move into a separate page
  site/content/contribute/webapp/build-component.md
  site/content/contribute/webapp/unit-testing.md
Labels: Ready to Merge, content
