Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-05, with the labels that each got.

#277 update carlos panato dev areas
  site/content/contribute/getting-started/core-committers.md
Labels: 2: Dev Review

#276 Add env vars for iOS Notification Service Extension
  site/content/contribute/mobile/build-your-own/environment-vars.md
Labels: 3: Ready to Merge

#274 Update help wanted issue queries
  site/content/contribute/desktop/_index.md
  site/content/contribute/getting-started/_index.md
  site/content/contribute/mobile/_index.md
  site/content/contribute/redux/_index.md
  site/content/contribute/webapp/_index.md
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 3: Reviews Complete

#285 update plugins
  site/content/internal/infrastructure/plugins.md
Labels: 2: Dev Review

#287 Add doc on sustained engineering team
  site/content/internal/sustained-engineering.md
Labels: 2: Dev Review

#289 Add webapp test troubleshooting for Jest / Node v10 compatibility issues
  site/content/contribute/webapp/developer-setup.md
  site/content/contribute/webapp/unit-testing.md
  site/static/img/extend/jest-assertion-fails-nodeversion.png
Labels: 3: Reviews Complete

#288 Add support responses to SET doc
  site/content/internal/sustained-engineering.md
Labels: 3: Reviews Complete

#290 fix bullet formatting on Sustained Engineering Team
  site/content/internal/sustained-engineering.md
Labels: 2: Dev Review

#284 Adding Bob (QA) to Apps team
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete, Lifecycle/1:stale
