Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-07, with the labels that each got.

#313 MM-16557 Add homepage link to admin docs
  site/config.toml
  site/layouts/partials/head.html
Labels: 3: Reviews Complete

#307 Add best practive section about authentication of http requests
  site/content/extend/plugins/server/best-practices.md
Labels: 3: Reviews Complete

#315 MM-16704 Update per latest /cypress folder restructure
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 2: Dev Review

#319 Adding instructions for Cloud VPN configuration
  site/content/internal/infrastructure/vpn-cloud.md
  site/static/img/vpn_cloud_1.png
  site/static/img/vpn_cloud_2.png
  site/static/img/vpn_cloud_3.png
Labels: 2: Dev Review

#304 Create best-practices.md
  site/content/extend/plugins/best-practices.md
Labels: 3: Reviews Complete

#316 Remove /usr/local/go before installing over an existing version
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 3: Reviews Complete

#322 Small typos fixed in the documentation.
  site/content/contribute/desktop/code-signing.md
  site/content/contribute/desktop/developer-setup.md
  site/content/contribute/getting-started/labels.md
  site/content/extend/getting-started/_index.md
  site/content/internal/offboarding.md
  site/content/internal/sustained-engineering.md
Labels: 3: Reviews Complete

#328 Update example server test name and directory
  site/content/contribute/server/developer-workflow.md
Labels: 3: Reviews Complete

#333 Added images and cleaned up text
  site/content/extend/plugins/webapp/best-practices.md
  site/static/img/extend/bp-bottom-team-sidebar.png
  site/static/img/extend/bp-channel-header.png
  site/static/img/extend/bp-file-upload.png
  site/static/img/extend/bp-left-sidebar-header.png
  site/static/img/extend/bp-main-menu-action.png
  site/static/img/extend/bp-post-dropdown-menu.png
  site/static/img/extend/bp-slash-command.gif
  site/static/img/extend/bp-user-attributes.png
  site/static/img/extend/bp-user-popover.png
Labels: 1: Editor Review, 1: PM Review, 2: Dev Review

#324 Update labels.md
  site/content/contribute/getting-started/labels.md
Labels: 3: Reviews Complete

#326 Update assets-white-label.md
  site/content/contribute/mobile/build-your-own/assets-white-label.md
Labels: 3: Reviews Complete

#336 Require `2: QA Review` before merging
  site/content/contribute/getting-started/code-review.md
  site/content/contribute/getting-started/labels.md
Labels: 2: Dev Review

#323 Hermes at Chain React
  site/content/blog/2019-07-18-chain-react-2019.md
  site/content/blog/2019-07-18-chain-react-2019/hermes-build.gif
  site/content/blog/2019-07-18-chain-react-2019/hermes-stats.jpg
  site/content/blog/2019-07-18-chain-react-2019/thumbnail.png
Labels: 3: Reviews Complete

#337 Update cypress docs to indicate file naming
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 3: Reviews Complete

#338 Added engagio tracking scripts
  site/layouts/partials/head.html
Labels: 3: Reviews Complete

#334 Remove unnecessary word in sentence.
  site/content/contribute/redux/reducers.md
Labels: 3: Reviews Complete

#339 Fixed a broken link and several typos
  site/content/contribute/mobile/push-notifications/_index.md
  site/content/contribute/redux/_index.md
  site/content/contribute/server/rest-api.md
  site/content/contribute/webapp/developer-setup.md
  site/content/contribute/webapp/developer-workflow.md
  site/content/extend/plugins/community_process.md
  site/content/extend/plugins/server/ha.md
  site/content/integrate/slash-commands/_index.md
  site/content/internal/infrastructure/vpn.md
Labels: 3: Reviews Complete

#342 Updated QA testers
  site/content/contribute/getting-started/core-committers.md
Labels: 2: Dev Review
