Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-09, with the labels that each got.

#352 add Shota & Ben as Staff
  site/content/blog/2018-07-18-plugins-v2.md
  site/content/contribute/getting-started/core-committers.md
  site/content/extend/embed/_index.md
  site/content/extend/plugins/_index.md
  site/content/integrate/getting-started/_index.md
  site/content/internal/onboarding/new-staff-guide.md
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#353 add new step to generate the translation strings
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/webapp/developer-setup.md
  site/content/contribute/webapp/developer-workflow.md
Labels: 3: Reviews Complete

#295 Start best practice doc for webapp plugins
  site/content/extend/plugins/webapp/best-practices.md
  site/static/img/extend/bp-bottom-team-sidebar.png
  site/static/img/extend/bp-channel-header.png
  site/static/img/extend/bp-file-upload.png
  site/static/img/extend/bp-left-sidebar-header.png
  site/static/img/extend/bp-main-menu-action.png
  site/static/img/extend/bp-post-dropdown-menu.png
  site/static/img/extend/bp-slash-command.gif
  site/static/img/extend/bp-user-attributes.png
  site/static/img/extend/bp-user-popover.png
Labels: 3: Reviews Complete

#359 Update docs of test key in writing E2E
  site/content/contribute/getting-started/labels.md
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 1: Editor Review, 1: PM Review

#356 Update on-boarding guides
  site/content/internal/onboarding/manager-guide.md
  site/content/internal/onboarding/new-staff-guide.md
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#355 Added info about "props:card" option
  site/content/integrate/incoming-webhooks/_index.md
Labels: 3: Reviews Complete

#361 Add documentation for slash commands
  site/content/contribute/getting-started/branching.md
  site/content/contribute/getting-started/slash-commands.md
Labels: 2: Dev Review

#368 Update guidelines on E2E folder structure
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 3: Reviews Complete

#370 Update code-review.md
  site/content/contribute/getting-started/code-review.md
Labels: 3: Reviews Complete
