Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-03, with the labels that each got.

#245 update go ref to 1.12
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: Ready to Merge

#244 Formatting was a little off on docs
  site/content/contribute/mobile/developer-setup.md
Labels: Ready to Merge

#246 Add internal doc on adding plugins to community
  site/content/internal/infrastructure/plugins.md
Labels: Dev Review

#254 Cypress troubleshoot
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 2: Dev Review, Editor Review

#257 fix wrong cd path at step 8
  site/content/contribute/server/developer-setup/windows-wsl.md
  site/content/contribute/server/developer-setup/windows.md
Labels: 3: Ready to Merge

#248 re-structure mobile docs and added push notification service
  site/content/contribute/mobile/build-your-own.md
  site/content/contribute/mobile/build-your-own/_index.md
  site/content/contribute/mobile/build-your-own/android.md
  site/content/contribute/mobile/build-your-own/assets-white-label.md
  site/content/contribute/mobile/build-your-own/environment-vars.md
  site/content/contribute/mobile/build-your-own/ios.md
  site/content/contribute/mobile/build-your-own/preparation.md
  site/content/contribute/mobile/developer-setup/_index.md
  site/content/contribute/mobile/developer-setup/developer-workflow.md
  site/content/contribute/mobile/developer-setup/makefile.md
  site/content/contribute/mobile/developer-setup/run-on-device.md
  site/content/contribute/mobile/developer-setup/troubleshooting.md
  site/content/contribute/mobile/push-notifications/_index.md
  site/content/contribute/mobile/push-notifications/android.md
  site/content/contribute/mobile/push-notifications/ios.md
  site/content/contribute/mobile/push-notifications/migrate-gcm-fcm.md
  site/content/contribute/mobile/push-notifications/service.md
  site/layouts/partials/head.html
  site/layouts/partials/svg/exclamation.svg
  site/layouts/shortcodes/note.html
  site/static/css/note.css
  site/static/img/mobile/app_groups.png
  site/static/img/mobile/code_signing.png
  site/static/img/mobile/firebase_cloud_messaging.png
  site/static/img/mobile/firebase_console.png
  site/static/img/mobile/firebase_dashboard.png
  site/static/img/mobile/firebase_google_services.png
  site/static/img/mobile/firebase_project.png
  site/static/img/mobile/firebase_register_app.png
  site/static/img/mobile/firebase_sdk.png
  site/static/img/mobile/firebase_server_key.png
  site/static/img/mobile/firebase_settings.png
  site/static/img/mobile/ios_account.png
  site/static/img/mobile/ios_appid.png
  site/static/img/mobile/ios_create_push_certificate.png
  site/static/img/mobile/ios_csr.png
  site/static/img/mobile/ios_edit_appid.png
  site/static/img/mobile/ios_icloud.png
  site/static/img/mobile/ios_keychain_create_cert_request.png
  site/static/img/mobile/ios_keychain_export.png
  site/static/img/mobile/ios_keychain_export_password.png
  site/static/img/mobile/ios_keychain_export_save.png
  site/static/img/mobile/ios_keychain_request_certificate.png
  site/static/img/mobile/ios_keychain_save_cert_request.png
  site/static/img/mobile/ios_keychain_select.png
  site/static/img/mobile/ios_type.png
  site/static/img/mobile/ios_upload_csr.png
  site/static/img/mobile/manual_mpns.png
  site/static/img/mobile/proxy-config-android.png
  site/static/img/mobile/proxy-config.png
  site/static/img/mobile/push_contents.png
  site/static/img/mobile/running_ios.png
  site/static/img/mobile/sdk_platforms.png
  site/static/img/mobile/sdk_tools.png
  site/static/img/mobile/xcode_preferences.png
Labels: 3: Ready to Merge

#255 Update Contribution Checklist
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 3: Ready to Merge

#261 Fix typo in package name for utils
  site/content/contribute/server/_index.md
  site/content/contribute/server/developer-workflow.md
Labels: 2: Dev Review

#253 Create mobile-build-process.md
  site/content/internal/mobile-build-process/_index.md
  site/content/internal/mobile-build-process/bump-build-number.md
  site/content/internal/mobile-build-process/bump-version-number.md
  site/content/internal/mobile-build-process/troubleshooting.md
Labels: 3: Ready to Merge

#265 Fix install command
  site/content/contribute/desktop/developer-setup.md
Labels: 3: Ready to Merge

#263 CanSecWest 2019 encryption blog post
  site/content/blog/2019-04-25-cansecwest-2019-encryption.md
Labels: 2: Dev Review
