Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-04, with the labels that each got.

#267 Add R&D teams page
  site/content/internal/rd-teams.md
Labels: 1: PM Review, 2: Dev Review

#264 Fix FB and Twitter links in footer
  site/config.toml
  site/themes/config.toml
Labels: 3: Ready to Merge

#268 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 3: Ready to Merge

#266 Dependency management documentation.
  site/content/contribute/server/dependencies.md
Labels: 2: Dev Review

#270 Remove unnecessary backslash
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 3: Ready to Merge

#271 Add notes how to use bot accounts with slash commands
  site/content/integrate/slash-commands/_index.md
Labels: 3: Ready to Merge

#249 Update lifecycle time periods
  site/content/contribute/getting-started/inactive-contributions.md
Labels: 3: Ready to Merge

#247 document a proposed code review process
  site/content/contribute/getting-started/code-review.md
  site/content/contribute/getting-started/core-committers.md
  site/content/contribute/getting-started/labels.md
Labels: 1: Editor Review, 1: PM Review, 2: Dev Review

#272 Minor wording changes
  site/content/contribute/server/plugins.md
Labels: 3: Ready to Merge

#273 Update developer documentation
  site/content/contribute/server/developer-workflow.md
Labels: 2: Dev Review

#275 Add Stylianos to core committers and internal teams doc
  site/content/contribute/getting-started/core-committers.md
  site/content/internal/rd-teams.md
Labels: 3: Ready to Merge
