Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-06, with the labels that each got.

#296 Update Cocoapods version to 1.6.1
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 2: Dev Review

#294 Adding debugging instructions to plugin docs
  site/content/extend/plugins/server/debugging.md
Labels: 2: Dev Review

#298 Database replication strategies discussed at Percona Live 2019.
  site/content/blog/2019-06-04-percona-live-2019.md
  site/content/blog/2019-06-04-percona-live-2019/transaction-1.svg
  site/content/blog/2019-06-04-percona-live-2019/transaction-2.svg
  site/content/blog/2019-06-04-percona-live-2019/transaction-3.svg
  site/content/blog/2019-06-04-percona-live-2019/transaction-4.svg
  site/content/blog/2019-06-04-percona-live-2019/transaction-5.svg
  site/static/css/styles.css
Labels: 3: Reviews Complete

#301 Fix various links
  site/content/extend/customization/_index.md
  site/content/extend/getting-started/_index.md
Labels: 3: Reviews Complete

#299 Adds blog post about LDAP groups.
  site/content/blog/2019-06-05-ldap-nested-groups-modelling-and-representation-in-code.md
  site/static/img/nested-group-transposed.png
  site/static/img/nested-group.png
Labels: 3: Reviews Complete

#303 Changed github username.
  site/content/blog/2019-06-05-ldap-nested-groups-modelling-and-representation-in-code.md
  site/content/contribute/getting-started/core-committers.md
Labels: 2: Dev Review

#297 Starting server plugin best practice doc
  site/content/extend/plugins/server/best-practices.md
Labels: 3: Reviews Complete

#305 Bad link to contributions-without-ticket
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 3: Reviews Complete

#278 add ops/infra team
  site/content/internal/rd-teams.md
Labels: 2: Dev Review, Do Not Merge

#308 add Ali & Maria
  site/content/contribute/getting-started/core-committers.md
  site/content/internal/rd-teams.md
Labels: 2: Dev Review

#306 MM-16298 Document cherry-pick process.
  site/content/contribute/getting-started/branching-overview.png
  site/content/contribute/getting-started/branching.md
Labels: 3: Reviews Complete

#309 Update developer-setup.md
  site/content/contribute/webapp/developer-setup.md
Labels: 3: Reviews Complete

#310 Fix step numbers and fix code formatting in webapp/developer-setup
  site/content/contribute/webapp/developer-setup.md
Labels: 3: Reviews Complete

#311 Update references to "mattermost-plugin-sample" to be "mattermost-plugin-starter-template"
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/extend/plugins/_index.md
  site/content/extend/plugins/example-plugins.md
  site/content/extend/plugins/migration.md
  site/content/extend/plugins/overview/_index.md
  site/content/extend/plugins/server/hello-world.md
  site/content/extend/plugins/webapp/actions.md
  site/content/extend/plugins/webapp/hello-world.md
Labels: 3: Reviews Complete
