Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-10, with the labels that each got.

#375 Updated the order...
  site/content/contribute/server/developer-setup/windows.md
Labels: 2: Dev Review

#374 document plugin helpers methodology
  site/content/extend/plugins/helpers.md
Labels: 2: Dev Review

#373 Sidebar improvements
  site/content/extend/plugins/best-practices.md
  site/content/extend/plugins/overview.md
  site/layouts/partials/sidebar.html
Labels: 3: Reviews Complete

#372 Blog Post: Avoiding flaky tests.
  site/content/blog/2019-09-29-avoiding-flaky-tests.md
Labels: 3: Reviews Complete

#377 Document requirement to install docker-compose
  site/content/contribute/server/developer-setup/arch.md
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 3: Reviews Complete, Hacktoberfest

#381 add plugin helpers section
  scripts/plugin-godocs.go
  site/layouts/shortcodes/plugingodocs.html
Labels: 3: Reviews Complete, Hacktoberfest

#384 Fix typo in plugin documentation
  site/content/extend/plugins/helpers.md
Labels: 3: Reviews Complete

#386 Add 'How to update the config' to documentation
  site/content/contribute/server/system_console.md
Labels: 3: Reviews Complete, Hacktoberfest

#367 Quick fixes to the plugin process docs
  site/content/extend/plugins/community_process.md
Labels: 3: Reviews Complete

#390 Update contributions-without-ticket.md
  site/content/contribute/getting-started/contributions-without-ticket.md
Labels: 3: Reviews Complete

#389 Fixed Javascript Link
  site/content/contribute/mobile/_index.md
Labels: 3: Reviews Complete, Hacktoberfest

#382 Bump hugo version to 0.58.3
  .travis.yml
Labels: 3: Reviews Complete

#387 Get rid of GOPATH in the developers setup guide
  site/content/contribute/server/developer-setup/arch.md
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/osx.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
  site/content/contribute/server/developer-setup/windows.md
Labels: 3: Reviews Complete, Hacktoberfest

#393 add mattermost team contributors page
  site/content/contribute/team_contributions/_index.md
Labels: 3: Reviews Complete

#394 Blog Post: Debugging using Charles
  site/content/blog/2019-10-21-debugging-using-charles.md
  site/content/blog/2019-10-21-debugging-using-charles/configure-ssl-proxying.png
  site/content/blog/2019-10-21-debugging-using-charles/debugging-community.png
  site/content/blog/2019-10-21-debugging-using-charles/map-remote.png
  site/content/blog/2019-10-21-debugging-using-charles/map-remote.xml
  site/content/blog/2019-10-21-debugging-using-charles/proxying-community.png
  site/content/blog/2019-10-21-debugging-using-charles/proxying.png
Labels: 3: Reviews Complete

#396 Updating golang version.
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 3: Reviews Complete

#383 [MM-18676] Add tags to sort plugin server API methods
  scripts/plugin-godocs.go
  site/layouts/shortcodes/plugingodocs.html
Labels: 3: Reviews Complete, Hacktoberfest

#402 Update Cocoapods to 1.7.5
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 3: Reviews Complete

#391 update manager-guide github org membership
  site/content/internal/onboarding/manager-guide.md
Labels: 3: Reviews Complete

#409 Updated the URLs
  site/content/contribute/server/rest-api.md
Labels: 3: Reviews Complete, Hacktoberfest

#410 Update developer-workflow.md
  site/content/contribute/server/developer-workflow.md
Labels: 3: Reviews Complete

#408 Update new-staff-guide.md
  site/content/internal/onboarding/new-staff-guide.md
Labels: 3: Reviews Complete

#413 Add rest of platform team to core commiters page.
  site/content/contribute/getting-started/core-committers.md
Labels: 3: Reviews Complete

#407 Instrumenting your code with Go AST - Blog post
  site/content/blog/2019-10-25-instrumenting-go-code-via-ast.md
  site/content/blog/2019-10-25-instrumenting-go-code-via-ast/Abstract_syntax_tree_for_Euclidean_algorithm.png
  site/content/blog/2019-10-25-instrumenting-go-code-via-ast/hello_ast.png
Labels: 3: Reviews Complete

#412 Update build-component.md
  site/content/contribute/webapp/build-component.md
Labels: 3: Reviews Complete
