Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-02, with the labels that each got.

#223 update release process
  site/content/internal/release-process.md
Labels: Dev Review

#230 add other steps for release
  site/content/internal/release-process.md
Labels: Ready to Merge

#224 add dev setup for ubuntu 18.04
  site/content/contribute/server/developer-setup.md
Labels: Ready to Merge

#232 Add short steps on how to write a blog post
  site/content/internal/writing-a-blog-post.md
Labels: Dev Review

#236 Adding list of community maintainers
  site/content/contribute/getting-started/core-committers.md
Labels: Ready to Merge

#237 Add guideline on how to add test key and description to spec file
  site/content/contribute/webapp/end-to-end-tests.md
Labels: Dev Review, content

#239 Update push proxy instructions
  site/content/contribute/mobile/build-your-own.md
  site/static/img/farebase_server_key.png
  site/static/img/firebase_server_key.png
  site/static/img/proxy-config.png
Labels: Dev Review

#240 Added command to avoid permission issue while running docker
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/ubuntu.md
Labels: Hackfest, Ready to Merge

#241 Update core-committers.md
  site/content/contribute/getting-started/core-committers.md
Labels: Dev Review

#243 Update arguments sent in slash command request
  site/content/integrate/slash-commands/_index.md
Labels: Ready to Merge
