Repository mattermost/mattermost-developer-documentation, pull requests merged in 2019-01, with the labels that each got.

#211 Update onboarding.md
  site/content/internal/onboarding.md
Labels: Ready to Merge

#172 Dev Docs Updates
  site/content/contribute/server/developer-setup.md
  site/content/contribute/server/developer-setup/arch.md
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/osx.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
  site/content/contribute/server/developer-setup/windows.md
  site/content/contribute/webapp/developer-setup.md
  site/layouts/shortcodes/content.html
  site/static/css/styles.css
Labels: Dev Review

#212 Fix issue > contribution mistake
  site/content/contribute/getting-started/inactive-contributions.md
Labels: Ready to Merge

#213 Fix typos from $(go env GOPATH)/go to $(go env GOPATH)
  site/content/contribute/webapp/developer-setup.md
Labels: Dev Review

#214 Fix naming in Inactive Contributions
  site/content/contribute/getting-started/inactive-contributions.md
Labels: PM Review

#215 Add E2E troubleshooting
  site/content/contribute/webapp/end-to-end-tests.md
Labels: Ready to Merge

#210 MM-12244 Adding how to build and deploy a custom server
  site/content/extend/customization/_index.md
  site/content/extend/customization/server-build.md
  site/content/extend/customization/server-files.md
  site/content/extend/customization/webapp.md
Labels: Ready to Merge

#208 Updating pre-release URL to community
  site/content/blog/idiomatic-error-handling.md
  site/content/blog/plugins-v2.md
  site/content/blog/repo-split.md
  site/content/contribute/desktop/_index.md
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/getting-started/contributions-without-ticket.md
  site/content/contribute/getting-started/core-committers.md
  site/content/contribute/mobile/_index.md
  site/content/contribute/redux/_index.md
  site/content/contribute/redux/redux-to-flow.md
  site/content/contribute/server/developer-workflow.md
  site/content/contribute/server/plugins.md
  site/content/contribute/webapp/webapp-to-redux.md
  site/content/extend/embed/_index.md
  site/content/extend/plugins/_index.md
  site/content/integrate/getting-started/_index.md
  site/content/internal/release-process.md
Labels: Ready to Merge

#216 update vault documentation
  site/content/internal/infrastructure/vault.md
Labels: Dev Review

#221 document inspecting webviews
  site/content/contribute/desktop/debugging.md
  site/content/contribute/desktop/view-toggle-developer-tools.png
  site/content/contribute/desktop/webview-developer-tools.png
Labels: Ready to Merge

#220 Capture a lightning talk at MatterCon 2019 re: submitting great PRs.
  site/content/blog/2019-01-24-submitting-great-prs.md
Labels: Dev Review, Editor Review

#222 Update onboarding docs
  site/content/internal/onboarding/_index.md
  site/content/internal/onboarding/manager-guide.md
  site/content/internal/onboarding/new-staff-guide.md
Labels: Dev Review, Editor Review

#225 Fastlane env vars
  site/content/contribute/mobile/build-your-own.md
Labels: Dev Review

#226 Migrate plugin manifest references from yaml to JSON
  site/content/extend/plugins/server/hello-world.md
  site/content/extend/plugins/webapp/hello-world.md
Labels: Ready to Merge

#227 Update redux unit test location
  site/content/contribute/redux/actions.md
  site/content/contribute/redux/developer-workflow.md
  site/content/contribute/redux/selectors.md
Labels: Ready to Merge

#228 Add blog authors and other minor updates
  site/content/blog/2017-09-04-repo-split.md
  site/content/blog/2018-05-22-npm-v6.md
  site/content/blog/2018-06-25-subpath.md
  site/content/blog/2018-07-18-plugins-v2.md
  site/content/blog/2018-10-18-idiomatic-error-handling.md
  site/content/blog/2019-01-24-submitting-great-prs.md
  site/content/blog/welcome.md
  site/layouts/blog/single.html
  site/layouts/blog/summary.html
  site/static/css/styles.css
Labels: Dev Review, PM Review
