Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-11, with the labels that each got.

#715 Update single.html
  site/config.toml
  site/layouts/_default/taxonomy.html
  site/layouts/blog/single.html
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#726 Specify required language in code blocks
  site/content/contribute/redux/actions.md
  site/content/contribute/redux/react-redux.md
  site/content/integrate/outgoing-webhooks/_index.md
  site/content/integrate/slash-commands/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#725 Update feature-flags.md
  site/content/contribute/server/feature-flags.md
Labels: 1: Dev Review

#730 SEO Updates for canonical URLs, robots.txt, moved app scripts to footer
  site/config.toml
  site/layouts/partials/footer.html
  site/layouts/partials/head.html
  site/static/robots.txt
Labels: 4: Reviews Complete

#727 Update footer button transitions to match other website elements
  site/layouts/partials/footer.html
  site/static/css/styles.css
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#736 Add new mobile team members
  site/content/contribute/getting-started/core-committers.md
Labels: 4: Reviews Complete

#737 Update branching.md
  site/content/contribute/getting-started/branching.md
  site/content/internal/onboarding/new-staff-guide.md
Labels: 1: Dev Review

#731 mobile: Remove gcm_senderId referece and gcm to fcm migration
  site/content/contribute/mobile/push-notifications/android.md
  site/content/contribute/mobile/push-notifications/migrate-gcm-fcm.md
  site/static/scripts/sign-android
Labels: 4: Reviews Complete

#734 Update _index.md
  site/content/contribute/team_contributions/_index.md
Labels: 4: Reviews Complete

#708 (fix: #350, #678) Change NodeJS version from "recommended" to "required"
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete
