Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-10, with the labels that each got.

#688 typo and instructions
  site/content/contribute/mobile/build-your-own/preparation.md
Labels: 4: Reviews Complete

#694 Add website footer to blog section
  site/layouts/blog/list.html
  site/layouts/blog/single.html
Labels: 4: Reviews Complete, Hacktoberfest

#695 [GH-686] sorting blog posts by date
  site/layouts/blog/list.html
Labels: 4: Reviews Complete, Hacktoberfest

#683 Blog Post: Load testing
  .github/workflows/gh-pages-cleanup.yml
  .github/workflows/gh-pages.yml
  site/content/blog/2020-09-07-improving-performance-through-load-testing.md
  site/content/blog/2020-09-07-improving-performance-through-load-testing/actions-map.png
  site/content/blog/2020-09-07-improving-performance-through-load-testing/feedback-loop.png
  site/content/blog/2020-09-07-improving-performance-through-load-testing/graph.png
Labels: 4: Reviews Complete

#701 MM-29281 Cypress environment variables
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 4: Reviews Complete

#702 Removed the tab for windows in server setup
  site/content/contribute/server/developer-setup.md
  site/content/contribute/server/developer-setup/windows.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#703 MM-29337 Environment variables for Detox testing
  site/content/contribute/mobile/e2e/environment-vars.md
Labels: 4: Reviews Complete

#704 Add cinlloc to contributor wall of fame
  site/content/contribute/team_contributions/_index.md
Labels: 4: Reviews Complete

#697 Remove Plugin Release Process
  site/content/internal/plugin-release-process.md
Labels: 4: Reviews Complete

#698 Fixed #684 - We are Hiring banner reappearing issue
  site/static/js/main.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#710 Add comment indicator guide
  site/content/contribute/mobile/e2e/guide-for-writing.md
Labels: 1: Dev Review, 2: Editor Review, 3: QA Review

#711 Detox/E2E: Add more details about TM4J
  site/content/contribute/mobile/e2e/guide-for-writing.md
Labels: 4: Reviews Complete

#713 Update plugin contribution docs
  site/content/contribute/plugins/_index.md
  site/content/contribute/plugins/developer-setup.md
  site/content/contribute/plugins/help-wanted-tickets.md
Labels: 4: Reviews Complete

#667 Windows10 guide for Mattermost-Mobile version. Update _index.md
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete

#696 [MM-24391] Update docs to reflect allowing colons in icon_emoji names
  site/content/integrate/incoming-webhooks/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#717 Update footer.html
  site/layouts/partials/footer.html
Labels: Hacktoberfest, hacktoberfest-accepted

#716 Bump version to Mattermost 5.28.0
  go.mod
  go.sum
Labels: 4: Reviews Complete

#714 MM-28866 Basic usage of feature flags.
  site/content/contribute/server/feature-flags.md
Labels: 1: Dev Review, 2: Editor Review

#719 Fix image path for make i18n-extract docs
  site/content/contribute/webapp/using-i18n-extract.md
Labels: 4: Reviews Complete

#721 Adding vipul08 to contributor wall of fame
  site/content/contribute/team_contributions/_index.md
Labels: 4: Reviews Complete

#723 2020-10-28-docker-content-trust-in-gitlab-with-delegation
  site/content/blog/2020-10-28-docker-content-trust-in-gitlab-with-delegation.md
Labels: 4: Reviews Complete
