Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-02, with the labels that each got.

#513 Bump hugo version to 0.62.2
  .circleci/config.yml
Labels: 3: Reviews Complete

#523 Add make run
  Makefile
  legacy.mk
Labels: 3: Reviews Complete

#531 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 2: Dev Review

#530 Append a short description to branch names
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/server/developer-workflow.md
  site/content/contribute/webapp/developer-workflow.md
Labels: 3: Reviews Complete

#532 Adjust formatting for "Install dependencies"
  site/content/contribute/webapp/developer-setup.md
Labels: 3: Reviews Complete

#534 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 3: Reviews Complete

#529 Added minimum SW requirements to developer-setup
  site/content/contribute/server/developer-setup.md
Labels: 2: Dev Review, Lifecycle/1:stale

#498 generate empty mattermost.json if there is no changes
  .github/workflows/notify-mm-blog.yml
Labels: 3: Reviews Complete

#537 Add missing `make config-reset` to "useful make commands" in developer-workflow
  site/content/contribute/server/developer-workflow.md
Labels: 3: Reviews Complete

#540 Update developer-workflow.md
  site/content/contribute/webapp/developer-workflow.md
Labels: 3: Reviews Complete

#539 Update _index.md
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 3: Reviews Complete
