Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-01, with the labels that each got.

#472 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#477 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#476 Update core-committers.md
  site/content/contribute/getting-started/core-committers.md
Labels: 3: Reviews Complete

#478 Update writing-a-blog-post.md
  site/content/internal/writing-a-blog-post.md
Labels: 3: Reviews Complete

#480 Update contribution-checklist.md
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 3: Reviews Complete

#481 Allow two authors in Developers Blog
  site/content/internal/writing-a-blog-post.md
  site/layouts/blog/single.html
  site/layouts/partials/blogauthor.html
Labels: 3: Reviews Complete

#482 Additional env variable in mobile repo
  site/content/contribute/mobile/build-your-own/environment-vars.md
Labels: 3: Reviews Complete

#470 MM-20801 Adding blog for cloud monitoring
  site/content/blog/2019-12-18-cloud-monitoring.md
  site/content/blog/2019-12-18-cloud-monitoring/prometheus_federate.png
Labels: 3: Reviews Complete

#486 when checkout fetch the all history
  .github/workflows/notify-mm-blog.yml
Labels: 3: Reviews Complete

#490 Move Justine from "Other" to the relevant R&D teams
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#487 Update Security Team Entries
  site/content/internal/rd-teams.md
Labels: 2: Dev Review

#483 Add blog post about GolangCI-Lint
  site/content/blog/2020-01-13-incorporating-golangci-lint.md
Labels: 3: Reviews Complete

#495 Fix md formating for golangci-lint post
  site/content/blog/2020-01-13-incorporating-golangci-lint.md
Labels: 3: Reviews Complete

#492 Remove Plugin Signing
  site/content/extend/plugins/signing-plugins.md
Labels: 3: Reviews Complete

#496 Fix gh actions for blog posts
  .github/workflows/notify-mm-blog.yml
Labels: 3: Reviews Complete

#456 Add information on ``skip_slack_parsing``
  site/content/integrate/slash-commands/_index.md
Labels: 3: Reviews Complete

#494 Bump hugo version to 0.62.2
  .circleci/config.yml
Labels: 3: Reviews Complete

#467 Formalizing customer support tickets process with SET
  site/content/internal/sustained-engineering.md
Labels: 2: Dev Review

#509 Revert "Bump hugo version to 0.62.2 (#494)"
  .circleci/config.yml
Labels: 2: Dev Review

#503 MM-21107: eliminate duplicate API listing
  cmd/plugin-godocs/plugin-godocs.go
Labels: 3: Reviews Complete

#491 Fix two authors in list view
  site/layouts/blog/summary.html
Labels: 3: Reviews Complete

#508 Allow "unsafe" mode to use html in hugo source
  site/config.toml
Labels: 3: Reviews Complete

#507 Stopped the `):` from getting absorbed into the link
  site/content/contribute/server/developer-setup/ubuntu.md
Labels: 3: Reviews Complete

#515 Replace Carlos from mentions in cutting a release.
  site/content/internal/release-process.md
Labels: 3: Reviews Complete

#514 Push Notification Service update for Mobile Deployment Guide
  site/content/contribute/mobile/push-notifications/service.md
Labels: 3: Reviews Complete

#473 Onboarding with Mattermost Blog Post
  site/content/blog/2019-12-20-onboarding-with-mattermost.md
Labels: 3: Reviews Complete

#519 Updated the webapp developer docs to match #387
  site/content/contribute/webapp/developer-setup.md
Labels: 3: Reviews Complete

#521 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 2: Dev Review

#522 Update manager-guide.md
  site/content/internal/onboarding/manager-guide.md
Labels: 1: Editor Review

#526 correct endpoint request in slash command docs
  site/content/integrate/slash-commands/_index.md
Labels: 2: Dev Review

#525 MM-22187: switch to pkg.go.dev
  site/layouts/shortcodes/plugingodocs.html
Labels: 3: Reviews Complete
