Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-04, with the labels that each got.

#585 MM-23182 Adding documentation for community Grafana dashboards
  site/content/internal/infrastructure/grafana.md
Labels: 2: Dev Review

#588 fix plugin release example
  site/content/internal/plugin-release-process.md
Labels: 3: Reviews Complete

#589 Bump version to Mattermost 5.22-rc1
  go.mod
  go.sum
Labels: 3: Reviews Complete

#581 MM-23367 Add docs about test metadata on Cypress spec files
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 3: Reviews Complete

#587 Allow submitter of a PR to user /update-branch
  site/content/contribute/getting-started/slash-commands.md
Labels: 3: Reviews Complete

#561 Update contribution-checklist.md
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 3: Reviews Complete

#574 MM-23588: Document i18n-extract in Server workflow
  site/content/contribute/server/developer-workflow.md
Labels: 3: Reviews Complete

#570 WIP: Update Mattermost contributors page
  site/content/contribute/team_contributions/_index.md
Labels: 3: Reviews Complete

#591 [IS-314] Add github status for deployment
  .circleci/config.yml
Labels: 2: Dev Review

#594 Typo fix
  site/content/contribute/mobile/push-notifications/service.md
Labels: 3: Reviews Complete

#596 Update contribution-checklist.md
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 3: Reviews Complete

#600 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#599 Update MVP
  site/content/contribute/mvp/_index.md
  site/content/contribute/team_contributions/_index.md
Labels: 3: Reviews Complete

#601 Include --force and --commitSHA examples
  site/content/internal/plugin-release-process.md
Labels: 2: Dev Review, 3: Reviews Complete

#605 add information about the chewbacca image
  site/content/contribute/containers/_index.md
Labels: 3: Reviews Complete

#606 update cloud vpn guide with pritunl
  site/content/internal/infrastructure/vpn-cloud.md
  site/static/img/vpn_cloud_10.jpg
  site/static/img/vpn_cloud_11.jpg
  site/static/img/vpn_cloud_4.png
  site/static/img/vpn_cloud_5.jpg
  site/static/img/vpn_cloud_6.jpg
  site/static/img/vpn_cloud_7.jpg
  site/static/img/vpn_cloud_8.jpg
  site/static/img/vpn_cloud_9.jpg
Labels: 1: Editor Review, 2: Dev Review

#608 Adding myself as a designer in the workflow team
  site/content/internal/rd-teams.md
Labels: 3: Reviews Complete

#603 Make Go installation step version independant
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 3: Reviews Complete

#573 windows-build-tools
  site/content/contribute/desktop/developer-setup.md
Labels: 3: Reviews Complete

#609 Add documentation on proxy support
  site/content/contribute/mobile/push-notifications/service.md
Labels: 3: Reviews Complete

#598 Add missing WSL and Docker for Windows configuration steps.
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 3: Reviews Complete

#602 GH-388: Documentation added for `make i18n-extract`.
  site/content/contribute/webapp/using-i18n-extract.md
  site/content/contribute/webapp/webapp-to-redux.md
  site/static/img/i18n-extract-1.jpg
  site/static/img/i18n-extract-2.jpg
  site/static/img/i18n-extract-3.jpg
  site/static/img/i18n-extract-4.jpg
Labels: 3: Reviews Complete

#584 3: QA Review
  site/content/contribute/getting-started/code-review.md
  site/content/contribute/getting-started/labels.md
Labels: 3: Reviews Complete
