Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-07, with the labels that each got.

#649 Add link to Russian translation
  site/content/blog/2020-05-20-hands-on-iouring-go.md
Labels: 4: Reviews Complete

#651 Update new-staff-guide.md
  site/content/internal/onboarding/new-staff-guide.md
Labels: 4: Reviews Complete

#653 Adding @avasconcelos114 as core committer for webapp and mobile repos
  site/content/contribute/getting-started/core-committers.md
Labels: 4: Reviews Complete

#654 Fix formatting of new core committer
  site/content/contribute/getting-started/core-committers.md
Labels: 4: Reviews Complete

#655 Bump version to Mattermost 5.24.2
  go.mod
  go.sum
Labels: 4: Reviews Complete

#549 Add "Layered Store and struct embedding" blog post
  site/content/blog/2020-02-26-layered-store-and-struct-embedding.md
  site/content/blog/2020-02-26-layered-store-and-struct-embedding/layers.png
Labels: 1: Dev Review, Awaiting Submitter Action

#656 Remove "Migrate redux to flow" page and add "Migrate webapp to typescript" page
  site/content/contribute/redux/redux-to-flow.md
  site/content/contribute/webapp/migrating-to-typescript.md
Labels: 4: Reviews Complete

#660 Update Cypress E2E docs
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 4: Reviews Complete

#658 Add @abdulsmapara as a platform contributor
  site/content/contribute/team_contributions/_index.md
Labels: 4: Reviews Complete

#665 Adding we’re hiring notification banner
  site/config.toml
  site/layouts/partials/nav.html
  site/layouts/partials/nav2.html
  site/layouts/partials/notification.html
  site/static/css/bar.css
  site/static/css/styles.css
  site/static/js/main.js
Labels: 1: Dev Review
