Repository mattermost/mattermost-developer-documentation, pull requests merged in 2020-08, with the labels that each got.

#664 add nameserver for resolution in cloud pritunl
  site/content/internal/infrastructure/vpn-cloud.md
Labels: 4: Reviews Complete

#671 Update list of contributors
  site/content/contribute/team_contributions/_index.md
Labels: 4: Reviews Complete

#674 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#675 Bump version to Mattermost 5.26.0
  go.mod
  go.sum
Labels: 1: Dev Review

#669 Document how to apply the source available license
  site/content/extend/plugins/source-available-license.md
  site/content/extend/plugins/source-available-license/LICENSE
Labels: 4: Reviews Complete

#652 Update process to request a review of a brand new plugin
  site/content/extend/plugins/best-practices.md
Labels: 1: Dev Review

#676 Fix community.mattermost.com signup link
  site/content/integrate/getting-started/_index.md
  site/layouts/blog/single.html
  site/layouts/partials/blogauthor.html
Labels: 4: Reviews Complete

#661 Update plugin dev setup docs. Also add link to plugin docs in contribution docs
  site/content/contribute/desktop/_index.md
  site/content/contribute/getting-started/_index.md
  site/content/contribute/mobile/_index.md
  site/content/contribute/plugins/_index.md
  site/content/contribute/plugins/developer-setup.md
  site/content/contribute/plugins/help-wanted-tickets.md
  site/content/contribute/redux/_index.md
  site/content/contribute/server/_index.md
  site/content/contribute/webapp/_index.md
  site/content/extend/plugins/developer-setup.md
  site/content/extend/plugins/developer-workflow.md
  site/content/extend/plugins/webapp/best-practices.md
Labels: 1: PM Review
