Repository mattermost/mattermost-developer-documentation, pull requests merged in 2021-01, with the labels that each got.

#749 Update ios.md
  site/content/contribute/mobile/build-your-own/ios.md
Labels: 4: Reviews Complete

#741 Add blog post about common i18n mistakes
  site/content/blog/2020-12-04-common-i18n-mistakes.md
Labels: 1: Dev Review, 2: Editor Review

#724 Change plugin dev command `make debug-plugin` to `make attach-headless`
  site/content/extend/plugins/developer-workflow.md
Labels: 4: Reviews Complete

#738 Update rd-teams.md
  site/content/internal/rd-teams.md
Labels: 4: Reviews Complete

#744 SEO Updates - Url Corrections Missing Terminating Slash
  site/config.toml
  site/content/contribute/desktop/code-signing.md
  site/content/contribute/getting-started/_index.md
  site/content/contribute/getting-started/code-review.md
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/mobile/build-your-own/_index.md
  site/content/contribute/mobile/build-your-own/white-label.md
  site/content/contribute/mobile/e2e/guide-for-writing.md
  site/content/contribute/mobile/push-notifications/_index.md
  site/content/contribute/mobile/push-notifications/android.md
  site/content/contribute/mobile/push-notifications/corporate-proxy.md
  site/content/contribute/mobile/push-notifications/ios.md
  site/content/contribute/mobile/push-notifications/service.md
  site/content/contribute/mobile/unsigned/_index.md
  site/content/contribute/mobile/unsigned/android.md
  site/content/contribute/mobile/unsigned/ios.md
  site/content/contribute/plugins/_index.md
  site/content/contribute/redux/_index.md
  site/content/contribute/redux/actions.md
  site/content/contribute/redux/developer-setup.md
  site/content/contribute/redux/react-redux.md
  site/content/contribute/redux/reducers.md
  site/content/contribute/redux/selectors.md
  site/content/contribute/server/cli-commands.md
  site/content/contribute/server/plugins.md
  site/content/contribute/server/rest-api.md
  site/content/contribute/webapp/_index.md
  site/content/contribute/webapp/build-component.md
  site/content/contribute/webapp/developer-setup.md
  site/content/contribute/webapp/webapp-to-redux.md
  site/content/extend/customization/_index.md
  site/content/extend/getting-started/_index.md
  site/content/extend/plugins/_index.md
  site/content/extend/plugins/developer-setup.md
  site/content/extend/plugins/example-plugins.md
  site/content/extend/plugins/overview.md
  site/content/extend/plugins/server/hello-world.md
  site/content/extend/plugins/webapp/actions.md
  site/content/extend/plugins/webapp/hello-world.md
  site/content/integrate/getting-started/_index.md
  site/content/integrate/getting-started/how-should-i-integrate.md
  site/content/integrate/outgoing-webhooks/_index.md
  site/content/internal/infrastructure/aws.md
  site/content/internal/infrastructure/kubernetes/kubernetes-troubleshooting.md
  site/content/internal/mobile-build-process/_index.md
  site/content/internal/onboarding/manager-guide.md
Labels: 4: Reviews Complete

#753 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 2: Editor Review

#755 Fixing links to download app signing scripts
  site/content/contribute/mobile/unsigned/android.md
  site/content/contribute/mobile/unsigned/ios.md
Labels: 4: Reviews Complete

#751 MM-31917: Publish style guide
  site/content/contribute/server/style-guide.md
Labels: 4: Reviews Complete

#759 Bump up minimum required Go version
  site/content/contribute/server/developer-setup.md
Labels: 4: Reviews Complete
