Repository mattermost/mattermost-developer-documentation, pull requests merged in 2021-08, with the labels that each got.

#834 Added unknown CA troubleshooting
  site/content/contribute/mobile/push-notifications/service.md
Labels: 4: Reviews Complete

#670 Update community-plugin-marketplace.md
  site/content/extend/plugins/community-plugin-marketplace.md
Labels: 4: Reviews Complete

#867 update bot account creation and UI sections
  site/content/integrate/admin-guide/admin-bot-accounts/_index.md
Labels: 1: PM Review, Docathon 2021

#875 Updated Depreciated Links in admin-webhooks-incoming _index.md
  site/content/integrate/admin-guide/admin-webhooks-incoming/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#876 Updated broken links in admin-webhooks-outgoing _index.md
  site/content/integrate/admin-guide/admin-webhooks-outgoing/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#865 remove reference to "available in future" line
  site/content/integrate/apps/_index.md
Labels: 4: Reviews Complete

#877 updated broken links in admin-bot-accounts _index.md
  site/content/integrate/admin-guide/admin-bot-accounts/_index.md
Labels: 2: Editor Review, Docathon 2021

#874 Updated deprecated links in admin-slash-commands _index.md
  site/content/integrate/admin-guide/admin-slash-commands/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#904 Update _index.md / Slash Commands
  site/content/integrate/slash-commands/_index.md
Labels: 2: Editor Review, Docathon 2021

#902 Update _index.md
  site/content/integrate/examples/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#896 Updated contribute/desktop _index.md
  site/content/contribute/desktop/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#892 Updated the deprecated link in admin-interactive-messages _index.md
  site/content/integrate/admin-guide/admin-interactive-messages/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#905 Update _index.md / Plugins
  site/content/extend/getting-started/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#894 Updated contribute/containers _index.md
  site/content/contribute/containers/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#890 Update developer-setup.md
  site/content/extend/plugins/developer-setup.md
Labels: 4: Reviews Complete, Docathon 2021

#888 Updated the deprecated link in integrating/getting-started _index.md
  site/content/integrate/getting-started/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#887 Updated deprecated links in integrate/slash_commands _index.md
  site/content/integrate/slash-commands/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#883 adding meta redirect to handbook
  site/content/internal/plugin-release-process.md
  site/content/internal/rd-teams.md
Labels: 4: Reviews Complete, Docathon 2021

#878 Updated deprecated links in outgoing-webhooks _index.md
  site/content/integrate/outgoing-webhooks/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#879 Updated deprecated links in incoming-webhooks _index.md
  site/content/integrate/incoming-webhooks/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#882 Updated deprecated links in admin-interactive-dialogs _index.md
  site/content/integrate/admin-guide/admin-interactive-dialogs/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#909 Include info about running plugins with scheduled jobs in HA
  site/content/extend/plugins/server/ha.md
Labels: 4: Reviews Complete, Docathon 2021

#891 Update corporate-proxy.md
  site/content/contribute/mobile/push-notifications/corporate-proxy.md
Labels: 4: Reviews Complete, Docathon 2021

#880 Updated deprecated links in admin-guide _index.md
  site/content/integrate/admin-guide/_index.md
Labels: 4: Reviews Complete, Docathon 2021

#871 Add Style related documentation on interactive message buttons
  site/content/integrate/admin-guide/admin-interactive-messages/_index.md
  site/content/integrate/admin-guide/admin-interactive-messages/interactive_button_style.png
  site/content/integrate/admin-guide/admin-interactive-messages/interactive_message.gif
Labels: 4: Reviews Complete, Docathon 2021

#912 Update Content in Developer Guide.
  site/content/integrate/admin-guide/_index.md
Labels: 1: Dev Review

#914 Fix Integrate & Extend Top Nav
  site/config.toml
Labels: 4: Reviews Complete

#917 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#872 Update slash commands _index.md
  site/content/integrate/admin-guide/admin-slash-commands/_index.md
Labels: 4: Reviews Complete

#745 MM-21543 [Hackathon Dec-2020] Update Cypress E2E documentation
  site/content/contribute/mobile/e2e/guide-for-writing.md
  site/content/contribute/webapp/e2e-cheatsheet/_index.md
  site/content/contribute/webapp/e2e-cheatsheet/account-settings-modal.md
  site/content/contribute/webapp/e2e-cheatsheet/account-settings-modal.png
  site/content/contribute/webapp/e2e-cheatsheet/basic-code-structure.md
  site/content/contribute/webapp/e2e-cheatsheet/channel-menu.md
  site/content/contribute/webapp/e2e-cheatsheet/channel-menu.png
  site/content/contribute/webapp/e2e-cheatsheet/main-menu.md
  site/content/contribute/webapp/e2e-cheatsheet/main-menu.png
  site/content/contribute/webapp/e2e/_index.md
  site/content/contribute/webapp/e2e/folder-and-file-structure.md
  site/content/contribute/webapp/e2e/guide-for-writing.md
  site/content/contribute/webapp/e2e/interested-in-contributing.md
  site/content/contribute/webapp/e2e/running-e2e.md
  site/content/contribute/webapp/e2e/troubleshooting.md
  site/content/contribute/webapp/e2e/which-query-to-use.md
  site/content/contribute/webapp/end-to-end-tests.md
Labels: 2: Editor Review

#828 [MM-34622] add hello webhooks docs
  site/content/integrate/apps/using-third-party-api/_index.md
  site/content/integrate/apps/using-third-party-api/hello-oauth2/_index.md
  site/content/integrate/apps/using-third-party-api/hello-webhooks/_index.md
  site/content/integrate/apps/using-third-party-api/hello-webhooks/received-webhook.png
  site/content/integrate/apps/using-third-party-api/hello-webhooks/sent-webhook.png
Labels: 4: Reviews Complete

#885 Updated actions.md for Redux Interactions
  site/content/integrate/plugins/webapp/actions.md
Labels: 1: Dev Review, preview-environment, Docathon 2021

#836 Add rest argument for commands.
  site/content/integrate/apps/interactivity/_index.md
Labels: 4: Reviews Complete, Docs/Done

#918 clarify cherry-pick happy path
  site/content/contribute/getting-started/branching.md
Labels: 4: Reviews Complete

#922 Add localization documentation
  site/content/integrate/apps/call/_index.md
Labels: 4: Reviews Complete
