Repository mattermost/mattermost-developer-documentation, pull requests merged in 2021-06, with the labels that each got.

#792 CR migration blog post
  site/content/blog/2021-04-16-migrating-operator-custom-resource/deployment-replica-sets-pods.png
  site/content/blog/2021-06-01-migrating-operator-custom-resource.md
Labels: 4: Reviews Complete

#842 Redirect R&D/core committers to handbook
  site/content/contribute/getting-started/core-committers.md
  site/content/internal/rd-teams.md
Labels: 4: Reviews Complete

#840 [MM-30595] Document relative icon paths for apps
  site/content/integrate/apps/bindings/_index.md
  site/content/integrate/apps/interactivity/_index.md
  site/content/integrate/apps/interactivity/example-post-menu/_index.md
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/quick-start-js/_index.md
  site/content/integrate/apps/using-third-party-api/_index.md
Labels: 2: Editor Review

#841 Document /apps install changes
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/quick-start-js/_index.md
  site/content/integrate/apps/using-third-party-api/_index.md
Labels: 4: Reviews Complete

#830 Remove submit_on_cancel and cancel_button from app form docs
  site/content/integrate/apps/interactivity/_index.md
Labels: 4: Reviews Complete

#844 Update contribution-checklist.md
  site/content/contribute/getting-started/code-review.md
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 1: Dev Review

#850 Update iOS env vars
  site/content/contribute/mobile/build-your-own/ios.md
Labels: 2: Editor Review

#849 Update android env vars
  site/content/contribute/mobile/build-your-own/android.md
Labels: 2: Editor Review

#843 [MM-34921] Document app icon
  site/content/integrate/apps/manifest/_index.md
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/quick-start-js/_index.md
Labels: 4: Reviews Complete

#851 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#852 Cross-link the perf review document
  site/content/contribute/server/style-guide.md
Labels: 4: Reviews Complete

#854 Mobile app to use node 16 and npm 7
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete

#853 Fix App quick start links to point to examples/go/hello-world instead of helloworld
  site/content/integrate/apps/bindings/_index.md
  site/content/integrate/apps/interactivity/_index.md
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/quick-start-js/_index.md
Labels: 4: Reviews Complete

#826 [MM-35593] Self-hosted documentation improvements
  site/content/integrate/apps/deployment-aws/_index.md
  site/content/integrate/apps/deployment-aws/deploy-to-aws/_index.md
  site/content/integrate/apps/deployment-aws/deploy-to-aws/provisioning-in-3rd-party-aws.png
  site/content/integrate/apps/deployment-aws/deploy-to-aws/provisioning-in-mm-aws.png
  site/content/integrate/apps/deployment-aws/hello-lambda/_index.md
  site/content/integrate/apps/deployment-aws/prepare-app/_index.md
  site/content/integrate/apps/deployment-http/_index.md
  site/content/integrate/apps/deployment/_index.md
  site/content/integrate/apps/manifest/_index.md
Labels: 4: Reviews Complete
