Repository mattermost/mattermost-developer-documentation, pull requests merged in 2021-11, with the labels that each got.

#958 Fix bot token expiry docs links
  site/content/integrate/admin-guide/admin-bot-accounts/_index.md
Labels: 4: Reviews Complete

#957 Update config.toml
  site/config.toml
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#953 Update _index.md
  site/content/integrate/admin-guide/examples/_index.md
Labels: 4: Reviews Complete

#954 [Fix #950] : Apps landing page improvements
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/app-action-zoomed-in.png
  site/content/integrate/apps/app-channel-header-zoomed-in.png
  site/content/integrate/apps/app-slash-command-zoomed-in.png
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#938 mmclient not found. appsclient found instead [Go lang Quick Start guide]
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/using-mattermost-api/_index.md
  site/content/integrate/apps/using-third-party-api/hello-oauth2/_index.md
  site/content/integrate/apps/using-third-party-api/hello-webhooks/_index.md
Labels: 4: Reviews Complete, Contributor

#965 Remove reference to Beta
  site/content/integrate/plugins/community-plugin-marketplace.md
Labels: 4: Reviews Complete

#963 Instruction to install node via nvm
  site/content/contribute/webapp/developer-setup.md
Labels: 4: Reviews Complete
