Repository mattermost/mattermost-developer-documentation, pull requests merged in 2021-04, with the labels that each got.

#781 Archive 2021 ideas list
  site/content/contribute/gsoc/_index.md
Labels: 4: Reviews Complete

#786 Update steps for updating GitLab Omnibus's changelog
  site/content/internal/gitlab-omnibus.md
Labels: 4: Reviews Complete

#788 [Fix #728]: Update contribution docs to encourage merging instead of rebase off master.
  site/content/contribute/getting-started/code-review.md
  site/content/contribute/server/developer-workflow.md
Labels: 4: Reviews Complete

#789 typo for osslsigncode
  site/content/contribute/desktop/code-signing.md
Labels: 4: Reviews Complete

#787 Add basic instructions on how to use Split for feature flags
  site/content/contribute/server/feature-flags.md
Labels: 2: Editor Review

#793 Add info about enabling plugin during manual installation
  site/content/extend/plugins/webapp/hello-world.md
Labels: 4: Reviews Complete

#783 MM-34362 Update web app developer setup for Node 14
  site/content/contribute/webapp/developer-setup.md
  site/content/contribute/webapp/unit-testing.md
  site/static/img/extend/jest-assertion-fails-nodeversion.png
Labels: 4: Reviews Complete

#785 Add link to ease iOS certification renewal.
  site/content/contribute/mobile/push-notifications/service.md
Labels: 4: Reviews Complete

#790 Add Apps documentation
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/developer-guide/_index.md
  site/content/integrate/apps/example-interactivity/_index.md
  site/content/integrate/apps/example-post-menu/_index.md
  site/content/integrate/apps/hello-world/_index.md
  site/content/integrate/apps/hello-world/modal.png
  site/content/integrate/apps/hello-world/submit.png
  site/content/integrate/apps/lifecycle/_index.md
  site/content/integrate/apps/lifecycle/install-mm-aws-app.png
  site/content/integrate/apps/lifecycle/provisioning-in-3rd-party-aws.png
  site/content/integrate/apps/lifecycle/provisioning-in-mm-aws.png
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/using-mattermost-api/_index.md
  site/content/integrate/apps/using-third-party-api/_index.md
Labels: 4: Reviews Complete

#796 Add weight to integrate docs
  site/content/integrate/apps/_index.md
  site/content/integrate/examples/_index.md
  site/content/integrate/getting-started/_index.md
  site/content/integrate/incoming-webhooks/_index.md
  site/content/integrate/outgoing-webhooks/_index.md
  site/content/integrate/rest-api/_index.md
  site/content/integrate/slash-commands/_index.md
Labels: 1: Dev Review

#782 MM-34362 Updated references to mattermost-redux in preparation for monorepo
  site/content/contribute/redux/_index.md
  site/content/contribute/redux/developer-setup.md
  site/content/contribute/redux/developer-workflow.md
  site/content/contribute/webapp/redux/_index.md
  site/content/contribute/webapp/redux/actions.md
  site/content/contribute/webapp/redux/react-redux.md
  site/content/contribute/webapp/redux/reducers.md
  site/content/contribute/webapp/redux/selectors.md
  site/content/contribute/webapp/webapp-to-redux.md
  site/content/extend/plugins/webapp/reference.md
Labels: 4: Reviews Complete

#797 [MM-34144] Rewrite hello world to quickstart guide
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/hello-world/_index.md
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/quick-start-go/command.png
  site/content/integrate/apps/quick-start-go/modal.png
  site/content/integrate/apps/quick-start-go/submit.png
Labels: 4: Reviews Complete

#795 Review of apps documentation
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/developer-guide/_index.md
Labels: 4: Reviews Complete

#798 Restructure apps docs
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/bindings/_index.md
  site/content/integrate/apps/call/_index.md
  site/content/integrate/apps/developer-guide/_index.md
  site/content/integrate/apps/example-interactivity/_index.md
  site/content/integrate/apps/interactivity/_index.md
  site/content/integrate/apps/interactivity/error3.png
  site/content/integrate/apps/interactivity/example-post-menu/_index.md
  site/content/integrate/apps/interactivity/example-post-menu/flow.png
  site/content/integrate/apps/lifecycle/_index.md
  site/content/integrate/apps/manifest/_index.md
  site/content/integrate/apps/using-mattermost-api/_index.md
  site/content/integrate/apps/using-third-party-api/_index.md
Labels: 4: Reviews Complete

#800 Fix LHS menu
  site/content/integrate/apps/bindings/_index.md
  site/content/integrate/apps/call/_index.md
  site/content/integrate/apps/interactivity/_index.md
  site/content/integrate/apps/interactivity/example-post-menu/_index.md
  site/content/integrate/apps/lifecycle/_index.md
  site/content/integrate/apps/manifest/_index.md
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/using-mattermost-api/_index.md
  site/content/integrate/apps/using-third-party-api/_index.md
Labels: 1: PM Review

#762 Document our Guilds.
  site/content/contribute/getting-started/guilds.md
Labels: 4: Reviews Complete

#805 Update apps docs
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/bindings/_index.md
  site/content/integrate/apps/call/_index.md
  site/content/integrate/apps/deployment/_index.md
  site/content/integrate/apps/deployment/provisioning-in-3rd-party-aws.png
  site/content/integrate/apps/deployment/provisioning-in-mm-aws.png
  site/content/integrate/apps/interactivity/_index.md
  site/content/integrate/apps/lifecycle/_index.md
  site/content/integrate/apps/manifest/_index.md
Labels: 4: Reviews Complete

#750 update docs and screenshots around iOS notifications / certificates
  site/content/contribute/mobile/push-notifications/ios.md
  site/content/contribute/mobile/push-notifications/service.md
  site/static/img/mobile/apns.png
  site/static/img/mobile/choose_app_id.png
  site/static/img/mobile/ios_appid.png
  site/static/img/mobile/ios_create_push_certificate.png
  site/static/img/mobile/ios_csr.png
  site/static/img/mobile/ios_edit_appid.png
  site/static/img/mobile/ios_new_certificate.png
  site/static/img/mobile/ios_type.png
  site/static/img/mobile/ios_upload_csr.png
Labels: 4: Reviews Complete

#806 [MM-35251] Add JavaScript Apps quick start guide
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/quick-start-js/_index.md
  site/content/integrate/apps/quick-start-js/command.png
  site/content/integrate/apps/quick-start-js/modal.png
  site/content/integrate/apps/quick-start-js/submit.png
Labels: 1: Dev Review

#808 [MM-35184] Update apps install command
  site/content/integrate/apps/quick-start-go/_index.md
  site/content/integrate/apps/using-third-party-api/_index.md
Labels: 4: Reviews Complete

#804 Update _index.md
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/bindings/_index.md
  site/content/integrate/getting-started/how-should-i-integrate.md
Labels: 4: Reviews Complete
