Repository mattermost/mattermost-developer-documentation, pull requests merged in 2021-07, with the labels that each got.

#837 Add markdown field documentation
  site/content/integrate/apps/interactivity/_index.md
Labels: 4: Reviews Complete, Docs/Done

#858 Drop codeowners and general cleanup
  .github/workflows/gh-pages-cleanup.yml
  .github/workflows/gh-pages.yml
  .github/workflows/notify-mm-blog.yml
  CODEOWNERS
  Makefile
  legacy.mk
Labels: 4: Reviews Complete

#859 use the same way that is used in mattermost/docs to generate the preview site
  .circleci/config.yml
  .github/workflows/check-label.yml
  .github/workflows/gh-pages-cleanup.yml
  .github/workflows/gh-pages.yml
  .github/workflows/preview-env-fork.yml
  .github/workflows/preview-env.yml
Labels: 1: Dev Review

#863 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#862 Remove duplicate table entry
  site/content/integrate/apps/call/_index.md
Labels: 4: Reviews Complete

#857 Fix "We're hiring" banner permalink issue and markdown table word wrap
  site/static/css/bar.css
  site/static/css/styles.css
Labels: 4: Reviews Complete

#855 add multiselect to document
  site/content/integrate/apps/interactivity/_index.md
Labels: 4: Reviews Complete
