Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-01, with the labels that each got.

#971 fix small typo
  site/content/integrate/admin-guide/admin-interactive-dialogs/_index.md
Labels: 4: Reviews Complete, Contributor

#972 Terminology Updates
  site/content/contribute/mobile/push-notifications/service.md
  site/content/contribute/webapp/e2e-cheatsheet/account-settings-modal.png
  site/content/contribute/webapp/e2e-cheatsheet/channel-menu.md
  site/content/contribute/webapp/e2e-cheatsheet/channel-menu.png
  site/content/contribute/webapp/e2e-cheatsheet/main-menu.md
  site/content/contribute/webapp/e2e-cheatsheet/main-menu.png
  site/content/contribute/webapp/e2e-cheatsheet/product-menu.md
  site/content/contribute/webapp/e2e-cheatsheet/product-menu.png
  site/content/contribute/webapp/e2e-cheatsheet/settings-modal.md
  site/content/contribute/webapp/e2e-cheatsheet/settings-modal.png
  site/content/contribute/webapp/e2e/guide-for-writing.md
  site/content/integrate/admin-guide/admin-personal-access-token/_index.md
  site/content/integrate/admin-guide/admin-zapier-integration/_index.md
Labels: 4: Reviews Complete

#928 Update _index.md
  site/content/integrate/admin-guide/admin-plugins-beta/_index.md
Labels: 4: Reviews Complete

#976 Fix broken link to mobile app white label page
  site/content/contribute/mobile/build-your-own/android.md
Labels: 4: Reviews Complete

#980 Update index.md
  site/content/contribute/containers/_index.md
Labels: 2: Editor Review, Contributor

#984 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#979 BUG: Fixed
  site/content/contribute/getting-started/_index.md
Labels: 1: PM Review, Lifecycle/1:stale, Contributor

#990 replace circleci to use github actions and add internal deploy pipeline
  .circleci/config.yml
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/preview-env-fork.yml
  .github/workflows/preview-env.yml
  .gitlab-ci.yml
  go.mod
  go.sum
Labels: 4: Reviews Complete

#992 Clarify http response in interactive message docs
  site/content/integrate/admin-guide/admin-interactive-messages/_index.md
Labels: 4: Reviews Complete

#985 Update _index.md
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete, Contributor

#989 Typo Fixed
  site/content/blog/2017-09-04-repo-split.md
Labels: 4: Reviews Complete, Contributor

#988 Patch 1
  site/content/contribute/server/developer-setup/arch.md
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/osx.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 4: Reviews Complete, Contributor

#983 Remove extra newline to fix slash command table
  site/content/integrate/admin-guide/admin-slash-commands/_index.md
Labels: 2: Editor Review, Contributor

#982 Update slash-commands.md
  site/content/contribute/getting-started/slash-commands.md
Labels: Contributor

#1000 Added info about ANDROID_BUILD_TASK env var in building Android app docs
  site/content/contribute/mobile/build-your-own/android.md
Labels: 4: Reviews Complete, Contributor
