Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-12, with the labels that each got.

#1177 Update personal-server-setup-guide.md
  site/content/contribute/more-info/focalboard/personal-server-setup-guide.md
Labels: 4: Reviews Complete

#1180 Add missing feedback widget to the rest of the docs pages
  site/layouts/_default/single.html
Labels: 1: Dev Review, Contributor

#1186 MVP 7.5 updated
  site/content/contribute/more-info/mvp/_index.md
Labels: Contributor

#1189 App oauth2 example fix url
  site/content/integrate/apps/authentication/app-to-third-party/_index.md
Labels: 4: Reviews Complete

#1190 add instructions for manual cherry pick
  site/content/contribute/more-info/getting-started/branching.md
Labels: 4: Reviews Complete

#1175 Added links to the Handbook
  site/content/contribute/why-contribute/_index.md
Labels: 4: Reviews Complete

#1187 MM-49021 Update web app customization steps to account for products
  site/content/integrate/customization/customization/webapp.md
Labels: 4: Reviews Complete

#1172 Add new content for Apps Drivers
  site/content/integrate/apps/authentication/_index.md
  site/content/integrate/apps/authentication/app-to-third-party/_index.md
  site/content/integrate/apps/drivers/_index.md
  site/content/integrate/apps/drivers/golang.md
  site/content/integrate/apps/drivers/nodejs.md
  site/content/integrate/apps/functionality/external-webhooks/_index.md
  site/content/integrate/apps/functionality/kv-store.md
  site/content/integrate/apps/functionality/mattermost-api.md
  site/content/integrate/apps/functionality/oauth2.md
  site/content/integrate/apps/functionality/subscriptions.md
  site/content/integrate/apps/marketplace/_index.md
  site/content/integrate/apps/structure/bindings/embedded/_index.md
  site/content/integrate/apps/structure/bindings/embedded/embedded-binding-coffee-roast-example.png
  site/content/integrate/apps/structure/bindings/embedded/embedded-binding-example.png
  site/content/integrate/apps/structure/bindings/embedded/embedded-binding-select-example.png
  site/content/integrate/apps/structure/call-metadata/_index.md
  site/content/integrate/apps/structure/manifest/_index.md
  site/content/integrate/apps/testing/_index.md
  site/static/css/styles.css
Labels: 1: PM Review, 1: Dev Review, preview-environment
