Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-04, with the labels that each got.

#1052 Add test guideline when contributing code
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/getting-started/inactive-contributions.md
  site/content/contribute/getting-started/labels.md
  site/content/contribute/getting-started/test-guideline.md
  site/content/contribute/getting-started/test-servers.md
Labels: 4: Reviews Complete

#1055 [MM-34112] specify the user to run in the e2e/cypress directory
  site/content/contribute/webapp/e2e/running-e2e.md
Labels: 4: Reviews Complete

#1053 Add remoteMarketplace changes
  site/content/integrate/admin-guide/admin-plugins-beta/_index.md
Labels: 4: Reviews Complete

#1057 Add make store-mocks and make store-layers to the server workflow
  site/content/contribute/server/developer-workflow.md
Labels: 4: Reviews Complete

#1059 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#1058 Add note about MM_NO_DOCKER env var
  site/content/contribute/server/developer-workflow.md
Labels: 4: Reviews Complete

#1056 New MVP image
  site/content/contribute/mvp/_index.md
  site/static/img/mvp_award.png
Labels: 2: Editor Review

#1054 Update docs: deploy http
  site/content/integrate/apps/deploy/deploy-http/_index.md
Labels: 4: Reviews Complete, Contributor
