Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-03, with the labels that each got.

#1026 Update _index.md
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete

#1027 Remove research request, change it back to hiring
  site/config.toml
Labels: 2: Editor Review

#1019 Domain name changes in docs
  site/content/blog/2017-09-04-repo-split.md
  site/content/blog/2020-07-27-automated-ui-testing-with-cypress.md
  site/content/contribute/getting-started/contribution-checklist.md
  site/content/contribute/getting-started/contributions-without-ticket.md
  site/content/contribute/mobile/developer-setup/_index.md
  site/content/contribute/team_contributions/_index.md
  site/content/integrate/admin-guide/admin-embedding/_index.md
  site/content/integrate/admin-guide/admin-interactive-dialogs/_index.md
  site/content/integrate/admin-guide/admin-message-attachments/_index.md
  site/content/integrate/admin-guide/admin-personal-access-token/_index.md
  site/content/integrate/admin-guide/admin-plugins-beta/_index.md
  site/content/integrate/admin-guide/admin-slash-commands/_index.md
  site/content/integrate/admin-guide/admin-webhooks-incoming/_index.md
  site/content/integrate/admin-guide/admin-webhooks-outgoing/_index.md
  site/content/integrate/other-integrations/customization/_index.md
  site/content/integrate/other-integrations/customization/webapp.md
  site/content/integrate/other-integrations/incoming-webhooks/_index.md
  site/content/integrate/other-integrations/outgoing-webhooks/_index.md
  site/content/integrate/other-integrations/slash-commands/_index.md
  site/content/integrate/plugins/_index.md
  site/content/integrate/plugins/example-plugins.md
  site/content/internal/offboarding.md
Labels: 4: Reviews Complete

#1021 /contribute Redirect
  site/content/contribute/_index.md
Labels: 2: Editor Review

#1022 Update plugin contribution docs
  site/content/contribute/server/plugins.md
Labels: 4: Reviews Complete

#1012 MM-41988 Update legacy links for about.mattermost.com
  site/content/integrate/admin-guide/admin-personal-access-token/_index.md
  site/content/internal/offboarding.md
Labels: 4: Reviews Complete

#1020 Update onboarding docs
  site/content/contribute/getting-started/branching.md
  site/content/internal/onboarding/manager-guide.md
  site/content/internal/onboarding/new-staff-guide.md
Labels: 4: Reviews Complete

#1030 Remove mention of GOPATH
  site/content/contribute/server/developer-setup/arch.md
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/osx.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 4: Reviews Complete

#1032 Update dependencies page
  site/content/contribute/server/dependencies.md
Labels: 4: Reviews Complete

#995 Updated config.toml
  site/config.toml
Labels: 4: Reviews Complete, Contributor

#1036 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#1037 Update feature flags doc
  site/content/contribute/server/feature-flags.md
Labels: 4: Reviews Complete

#1038 Refresh code review guidelines
  site/content/contribute/getting-started/code-review.md
Labels: 4: Reviews Complete

#1034 Update system_console.md
  site/content/contribute/server/system_console.md
Labels: 4: Reviews Complete

#1035 Update cli-commands.md
  site/content/contribute/server/cli-commands.md
Labels: 4: Reviews Complete

#1040 Minor updates to the inactive contributions process
  site/content/contribute/getting-started/inactive-contributions.md
Labels: 2: Editor Review

#1043 Update dev talks page to point to the youtube playlist
  .gitignore
  Makefile
  cmd/devtalks/devtalks.go
  site/content/contribute/devtalks/_index.md
  site/layouts/shortcodes/devtalks.html
Labels: 4: Reviews Complete

#1046 Update _index.md
  site/content/contribute/team_contributions/_index.md
Labels: 4: Reviews Complete

#1042 Update guilds with latest information
  site/content/contribute/getting-started/guilds.md
Labels: 1: Dev Review, 2: Editor Review

#1048 updated e2e guide for writing
  site/content/contribute/mobile/e2e/guide-for-writing.md
  site/content/contribute/webapp/e2e/guide-for-writing.md
Labels: 4: Reviews Complete

#1050 Migrate in Focalboard developer documentation
  site/content/contribute/focalboard/_index.md
  site/content/contribute/focalboard/mattermost-boards-setup-guide.md
  site/content/contribute/focalboard/personal-server-setup-guide.md
  site/content/contribute/getting-started/_index.md
  site/content/integrate/plugins/community_process.md
Labels: 4: Reviews Complete

#1041 Mobile Apps Audit 2022
  site/content/contribute/mobile/_index.md
Labels: 4: Reviews Complete
