Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-11, with the labels that each got.

#1161 Merge the Apps Interactivity topic into the Structure topic
  site/content/integrate/apps/interactivity/_index.md
  site/content/integrate/apps/interactivity/error3.png
  site/content/integrate/apps/interactivity/example-post-menu/_index.md
  site/content/integrate/apps/interactivity/example-post-menu/flow.png
  site/content/integrate/apps/structure/_index.md
  site/content/integrate/apps/structure/bindings/_index.md
  site/content/integrate/apps/structure/bindings/embedded/_index.md
  site/content/integrate/apps/structure/bindings/embedded/embedded-binding-example.png
  site/content/integrate/apps/structure/bindings/embedded/embedded-binding-select-example.png
  site/content/integrate/apps/structure/call-metadata/_index.md
  site/content/integrate/apps/structure/call/_index.md
  site/content/integrate/apps/structure/forms/_index.md
  site/content/integrate/apps/structure/forms/click-channel-header-response-form.png
  site/content/integrate/apps/structure/forms/slash-command-autocomplete-modal-dialog.png
  site/content/integrate/apps/structure/forms/slash-command-autocomplete.png
  site/content/integrate/apps/structure/static-assets/_index.md
  site/content/integrate/slash-commands/_index.md
  site/static/css/styles.css
Labels: Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1155 Added workflow diagrams
  site/content/contribute/why-contribute/_index.md
  site/content/contribute/why-contribute/contribute.png
  site/content/contribute/why-contribute/inactivity.png
  site/content/contribute/why-contribute/review.png
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1168 Post Hacktoberfest banner update
  site/config.toml
Labels: 2: Editor Review

#1127 Update feature flags docs
  site/content/contribute/more-info/server/feature-flags.md
Labels: 4: Reviews Complete

#1169 Update incoming webhook response parameters
  site/content/integrate/webhooks/incoming/_index.md
  site/content/integrate/webhooks/outgoing/_index.md
Labels: preview-environment, Contributor

#1154 Added new Marketplace contribution page/section (Part 2)
  site/content/integrate/marketplace-submissions/_index.md
Labels: 1: PM Review, 1: Dev Review, preview-environment

#1162 Add site feedback widget
  site/layouts/_default/list.html
  site/layouts/partials/feedback.html
  site/layouts/partials/footer.html
  site/layouts/partials/head.html
  site/static/css/feedback.css
  site/static/css/styles.css
  site/static/js/feedback.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1173 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1174 Updated banner: improving dev experience
  site/config.toml
Labels: 1: Dev Review, 2: Editor Review

#1151 [GH-511]: Added workflow to check HTML using HTMLProofer
  .github/workflows/build.yml
  .gitignore
  .htmlvalidateignore
  Makefile
  package.json
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor
