Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-02, with the labels that each got.

#1002 Document supported OAuth2 flows
  site/content/integrate/admin-guide/admin-oauth2/_index.md
Labels: 4: Reviews Complete

#1010 Fix menu styles for smaller breakpoints
  site/layouts/partials/nav.html
  site/static/css/styles.css
Labels: 4: Reviews Complete

#1005 Known issue jira key
  site/content/contribute/mobile/e2e/guide-for-writing.md
  site/content/contribute/webapp/e2e/guide-for-writing.md
Labels: 4: Reviews Complete

#987 [MM-40821] contribute/server/schema-migration-guide: expand with new migration sys
  site/content/contribute/server/schema-migration-guide.md
Labels: 4: Reviews Complete

#1014 Fix header permalinks
  site/static/css/bar.css
Labels: 4: Reviews Complete

#1016 Update config.toml
  site/config.toml
Labels: 2: Editor Review, preview-environment

#1009 Update _index.md
  site/content/integrate/admin-guide/admin-oauth2/_index.md
Labels: 4: Reviews Complete, Contributor

#1004 docs(plugins): enable plugin uploads for dev setup
  site/content/integrate/plugins/developer-setup.md
Labels: 4: Reviews Complete, Contributor

#998 Update link url
  site/content/contribute/getting-started/contribution-checklist.md
Labels: 4: Reviews Complete, Contributor

#1018 Update community_process.md
  site/content/integrate/plugins/community_process.md
Labels: 4: Reviews Complete

#1013 Add info to customize Makefile and docker-compose
  site/content/contribute/server/developer-workflow.md
Labels: 4: Reviews Complete

#999 Update branching doc
  site/content/contribute/getting-started/branching.md
Labels: 1: Dev Review

#977 Delete blank page in app development docs
  site/content/integrate/apps/devenv/_index.md
Labels: 4: Reviews Complete

#1006 [Docs]: Updating Label
  site/content/contribute/getting-started/labels.md
Labels: 4: Reviews Complete, Contributor

#1024 Update _index.md
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete
