Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-10, with the labels that each got.

#1110 Update macos.md - M1 arch
  site/content/contribute/more-info/desktop/developer-setup/macos.md
Labels: 4: Reviews Complete

#1124 Remove storybook step from local e2e setup
  site/content/contribute/more-info/webapp/e2e/running-e2e.md
Labels: 4: Reviews Complete

#1126 Remove storybook references
  site/content/contribute/more-info/webapp/e2e-cheatsheet/basic-code-structure.md
Labels: 4: Reviews Complete

#1125 Change Url pointing to cypress.json to point cypress.config.ts
  site/content/contribute/more-info/webapp/e2e/running-e2e.md
Labels: 4: Reviews Complete

#1128 Updated dev docs banner for Hacktoberfest 2022
  site/config.toml
Labels: 2: Editor Review

#1129 Auto-expand subtopics in sidebar for the Contribute section
  site/layouts/partials/sidebar.html
Labels: Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1131 Recursive sidebar menu
  site/layouts/_default/list.html
  site/layouts/_default/single.html
  site/layouts/partials/sidebar-v2-recurse.html
  site/layouts/partials/sidebar-v2.html
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1134 Update _index.md
  site/content/contribute/_index.md
  site/content/contribute/expectations/_index.md
  site/content/contribute/good-decisions/_index.md
  site/content/contribute/why-contribute/_index.md
Labels: 1: Dev Review, 2: Editor Review, preview-environment

#1106 Expand app quick start guides
  site/content/integrate/apps/_index.md
  site/content/integrate/apps/quickstart/_index.md
  site/content/integrate/apps/quickstart/quick-start-go/_index.md
  site/content/integrate/apps/quickstart/quick-start-js/_index.md
  site/content/integrate/apps/quickstart/quick-start-jwt/_index.md
  site/content/integrate/apps/quickstart/quick-start-jwt/response.png
  site/content/integrate/apps/quickstart/quick-start-python/_index.md
  site/content/integrate/apps/quickstart/quick-start-python/first.png
  site/content/integrate/apps/quickstart/quick-start-python/modal.png
  site/content/integrate/apps/quickstart/quick-start-python/response.png
  site/content/integrate/apps/quickstart/quick-start-serverless/_index.md
  site/content/integrate/apps/quickstart/quick-start-serverless/response.png
  site/content/integrate/apps/quickstart/quick-start-ts/_index.md
  site/content/integrate/apps/quickstart/quick-start-ts/install-command.png
  site/content/integrate/apps/quickstart/quick-start-ts/install-confirmation.png
  site/content/integrate/apps/quickstart/quick-start-ts/install-modal.png
  site/content/integrate/apps/quickstart/quick-start-ts/modal-display.png
  site/content/integrate/apps/quickstart/quick-start-ts/modal.png
  site/content/integrate/apps/quickstart/quick-start-ts/submit.png
Labels: 1: Dev Review, preview-environment

#1138 zapier-integration index.md updated
  site/content/integrate/zapier-integration/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1111 Create new content for Apps Structure topic
  Makefile
  site/config.toml
  site/content/integrate/apps/functionality/_index.md
  site/content/integrate/apps/structure/_index.md
  site/content/integrate/apps/structure/apps-calls_bindings_locations_v2.svg
  site/content/integrate/apps/structure/bindings/_index.md
  site/content/integrate/apps/structure/bindings/command_location_weather.png
  site/content/integrate/apps/structure/bindings/command_location_weather_week.png
  site/content/integrate/apps/structure/call-metadata/_index.md
  site/content/integrate/apps/structure/call/_index.md
  site/content/integrate/apps/structure/manifest/_index.md
  site/content/integrate/apps/structure/static-assets/_index.md
  site/layouts/partials/footer.html
  site/layouts/partials/head.html
  site/layouts/shortcodes/collapse.html
  site/layouts/shortcodes/compass-icon.html
  site/layouts/shortcodes/newtabref.html
  site/layouts/shortcodes/note.html
  site/static/css/compass-icons.css
  site/static/css/styles.css
  site/static/font/FontAwesome.otf
  site/static/font/compass-icons.eot
  site/static/font/compass-icons.svg
  site/static/font/compass-icons.ttf
  site/static/font/compass-icons.woff
  site/static/font/compass-icons.woff2
  site/static/font/fontawesome-webfont.eot
  site/static/font/fontawesome-webfont.svg
  site/static/font/fontawesome-webfont.ttf
  site/static/font/fontawesome-webfont.woff
  site/static/font/fontawesome-webfont.woff2
Labels: preview-environment, Contributor

#1156 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1160 chore(webapp): added note for apple silicon macs
  site/content/contribute/more-info/webapp/developer-setup.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1159 Wrong Golang Link In WSL Setup
  site/content/contribute/more-info/server/developer-setup/windows-wsl.md
Labels: Hacktoberfest, 2: Editor Review, hacktoberfest-accepted, preview-environment, Contributor

#1146 Update sign-android
  site/static/scripts/sign-android
Labels: 1: Dev Review, 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1150 Update .editorconfig
  .editorconfig
Labels: Hacktoberfest, 2: Editor Review, hacktoberfest-accepted, Contributor

#1147 Add alternate image texts
  site/content/integrate/webhooks/incoming/_index.md
  site/content/integrate/webhooks/outgoing/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1122 <kbd> tag added
  site/content/contribute/more-info/focalboard/personal-server-setup-guide.md
  site/content/contribute/more-info/mobile/developer-setup/run.md
  site/content/contribute/more-info/webapp/developer-setup.md
  site/content/contribute/more-info/webapp/e2e/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1123 Fixed several broken links for developer setup
  site/content/contribute/more-info/server/developer-setup/arch.md
  site/content/contribute/more-info/server/developer-setup/centos.md
  site/content/contribute/more-info/server/developer-setup/osx.md
  site/content/contribute/more-info/server/developer-setup/ubuntu.md
  site/content/contribute/more-info/server/developer-setup/windows-wsl.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1152 Update mattermost-boards-setup-guide.md
  site/content/contribute/more-info/focalboard/mattermost-boards-setup-guide.md
Labels: 4: Reviews Complete

#1153 Zapier integration
  site/content/integrate/zapier-integration/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1130 Bump version to Mattermost 7.3.0
  .github/workflows/build.yml
  .gitlab-ci.yml
  go.mod
  go.sum
Labels: 4: Reviews Complete

#1148 [GH-1140] Formatted Notes and Tips across the developer documentation site
  site/content/blog/2020-03-15-instrumenting-go-code-via-ast-2.md
  site/content/contribute/expectations/_index.md
  site/content/contribute/more-info/desktop/debugging.md
  site/content/contribute/more-info/getting-started/contributions-without-ticket.md
  site/content/contribute/more-info/getting-started/inactive-contributions.md
  site/content/contribute/more-info/getting-started/test-guideline.md
  site/content/contribute/more-info/mobile/build-your-own/_index.md
  site/content/contribute/more-info/mobile/build-your-own/android.md
  site/content/contribute/more-info/mobile/build-your-own/ios.md
  site/content/contribute/more-info/mobile/build-your-own/white-label.md
  site/content/contribute/more-info/mobile/developer-setup/_index.md
  site/content/contribute/more-info/mobile/developer-setup/run.md
  site/content/contribute/more-info/mobile/push-notifications/service.md
  site/content/contribute/more-info/mobile/unsigned/_index.md
  site/content/contribute/more-info/mobile/unsigned/android.md
  site/content/contribute/more-info/mobile/unsigned/ios.md
  site/content/contribute/more-info/plugins/_index.md
  site/content/contribute/more-info/server/developer-setup/osx.md
  site/content/contribute/more-info/server/feature-flags.md
  site/content/contribute/more-info/webapp/redux/_index.md
  site/content/contribute/more-info/webapp/using-i18n-extract.md
  site/content/contribute/why-contribute/_index.md
  site/content/integrate/apps/authentication/app-to-mattermost/_index.md
  site/content/integrate/apps/authentication/oauth2/_index.md
  site/content/integrate/apps/quickstart/_index.md
  site/content/integrate/apps/structure/bindings/_index.md
  site/content/integrate/customization/customization/_index.md
  site/content/integrate/faq/_index.md
  site/content/integrate/plugins/community-plugin-marketplace.md
  site/content/integrate/plugins/components/server/hello-world.md
  site/content/integrate/plugins/components/webapp/reference.md
  site/content/integrate/plugins/developer-setup.md
  site/content/integrate/plugins/interactive-dialogs/_index.md
  site/content/integrate/plugins/using-and-managing-plugins.md
  site/content/integrate/reference/personal-access-token/_index.md
  site/content/integrate/webhooks/_index.md
  site/content/integrate/webhooks/outgoing/_index.md
  site/content/internal/infrastructure/vpn-cloud.md
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, Contributor

#1165 Removed $ signs so the commands can be copied with the UI copy button
  site/content/contribute/more-info/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete

#1135 Create and update content in the Apps Functionality topic
  site/content/integrate/apps/functionality/_index.md
  site/content/integrate/apps/functionality/external-webhooks/_index.md
  site/content/integrate/apps/functionality/external-webhooks/received-webhook.png
  site/content/integrate/apps/functionality/external-webhooks/sent-webhook.png
  site/content/integrate/apps/functionality/kv-store.md
  site/content/integrate/apps/functionality/mattermost-api.md
  site/content/integrate/apps/functionality/subscriptions.md
Labels: 1: PM Review, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1157 Add best practices and Hugo shortcodes to README.md
  README.md
  readme_assets/shortcode-collapse.png
  readme_assets/shortcode-compass-icon.png
  readme_assets/shortcode-mermaid.png
  readme_assets/shortcode-newtabref.png
  readme_assets/shortcode-note.png
Labels: 1: PM Review, Hacktoberfest, hacktoberfest-accepted, Contributor

#1167 Fix broken builds; webapp registry.js migrated to TypeScript
  scripts/package-lock.json
  scripts/package.json
  scripts/plugin-jsdocs.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor

#1166 Document what to do if a merged PR has a bug that was missed during PR reviews
  site/content/contribute/good-decisions/fixing-pr-mistakes.md
Labels: 1: Dev Review, Hacktoberfest, hacktoberfest-accepted, preview-environment, Contributor
