Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-08, with the labels that each got.

#1098 Improve docs build time
  Makefile
  scripts/package-lock.json
  scripts/package.json
  scripts/plugin-jsdocs.js
Labels: 4: Reviews Complete, Contributor

#1097 Hugo cleanup
  .github/workflows/build.yml
  .github/workflows/preview-env-fork.yml
  .github/workflows/preview-env.yml
  go.mod
  go.sum
  site/layouts/indexes/tag.html
  site/layouts/shortcodes/baseurl.html
  site/layouts/shortcodes/bignumber.html
  site/layouts/shortcodes/blogurl.html
  site/layouts/shortcodes/md.html
  site/themes/archetypes/default.md
  site/themes/config.toml
  site/themes/content/contribute/_index.md
  site/themes/layouts/404.html
  site/themes/layouts/_default/list.html
  site/themes/layouts/_default/single.html
  site/themes/layouts/index.html
  site/themes/layouts/partials/about.html
  site/themes/layouts/partials/contact.html
  site/themes/layouts/partials/counters.html
  site/themes/layouts/partials/footer.html
  site/themes/layouts/partials/head.html
  site/themes/layouts/partials/hero.html
  site/themes/layouts/partials/intro.html
  site/themes/layouts/partials/js.html
  site/themes/layouts/partials/nav.html
  site/themes/layouts/partials/nav2.html
  site/themes/layouts/partials/services.html
  site/themes/layouts/partials/testimonials.html
  site/themes/layouts/partials/work.html
Labels: 4: Reviews Complete, Contributor

#1103 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#1101 Remove golang-webhook page
  site/content/integrate/webhooks/_index.md
  site/content/integrate/webhooks/golang-webhook/_index.md
Labels: Contributor

#1077 Update service.md
  site/content/contribute/mobile/push-notifications/service.md
Labels: 1: Dev Review, Contributor

#1102 Fix broken links in contribute/server/developer-setup section
  site/content/contribute/server/developer-setup/arch.md
  site/content/contribute/server/developer-setup/centos.md
  site/content/contribute/server/developer-setup/osx.md
  site/content/contribute/server/developer-setup/ubuntu.md
  site/content/contribute/server/developer-setup/windows-wsl.md
Labels: 1: Dev Review, 2: Editor Review, preview-environment, Contributor

#1100 MM-20255 Update page on Redux actions and remove references to request state
  site/content/contribute/webapp/redux/actions.md
Labels: 4: Reviews Complete

#1029 Update labels page with new label and updated links
  site/content/contribute/getting-started/labels.md
Labels: 4: Reviews Complete

#1105 Combine various webhook content pages
  site/archive/incoming-webhooks/_index.md
  site/archive/outgoing-webhooks/_index.md
  site/archive/using-incoming-webhooks/_index.md
  site/archive/using-incoming-webhooks/incoming_webhooks_markdown_formatting.png
  site/archive/using-incoming-webhooks/incoming_webhooks_override_username.png
  site/archive/using-incoming-webhooks/incoming_webhooks_sample.png
  site/archive/using-outgoing-webhooks/_index.md
  site/content/integrate/apps/_index.md
  site/content/integrate/customization/_index.md
  site/content/integrate/webhooks/_index.md
  site/content/integrate/webhooks/incoming/_index.md
  site/content/integrate/webhooks/incoming/incoming_webhooks_create_simple.png
  site/content/integrate/webhooks/incoming/incoming_webhooks_full_example.png
  site/content/integrate/webhooks/outgoing/_index.md
  site/content/integrate/webhooks/outgoing/outgoing_webhooks_full_example.png
Labels: 4: Reviews Complete, Contributor

#1107 Fix instructions for creating personal access tokens
  site/content/integrate/reference/personal-access-token/_index.md
  site/content/integrate/reference/personal-access-token/access_token_manage_roles.png
  site/content/integrate/reference/personal-access-token/access_tokens_additional_roles.png
Labels: 4: Reviews Complete, Contributor
