Repository mattermost/mattermost-developer-documentation, pull requests merged in 2022-07, with the labels that each got.

#1088 Update folder structure of Cypress in mattermost-webapp
  site/content/contribute/webapp/e2e/folder-and-file-structure.md
  site/content/contribute/webapp/e2e/guide-for-writing.md
  site/content/contribute/webapp/e2e/running-e2e.md
Labels: 4: Reviews Complete

#1090 Update MVP
  site/content/contribute/mvp/_index.md
Labels: 4: Reviews Complete

#1087 Enable Notice.txt generation
  .config/notice-file/Readme.md
  .config/notice-file/config.yaml
  LICENSE.txt
  NOTICE.txt
Labels: 1: Dev Review

#1083 troubleshooting section for nvm
  site/content/contribute/mobile/developer-setup/_index.md
Labels: 4: Reviews Complete

#1080 update: focalboard instructions for prebuild for standalone desktop app dev setup
  site/content/contribute/focalboard/personal-server-setup-guide.md
Labels: 4: Reviews Complete, Contributor

#1093 Add where to fix translation
  site/content/contribute/getting-started/contributions-without-ticket.md
Labels: 4: Reviews Complete, Contributor
