Repository mattermost/mattermost-developer-documentation, pull requests merged in 2023-11, with the labels that each got.

#1312 Update notification banner
  site/config.toml
  site/layouts/partials/notification.html
  site/static/img/notification-bar/icon-green-rocket.svg
Labels: 2: Editor Review

#1311 Add prerequisites for WSL setup.
  site/content/contribute/developer-setup.md
Labels: 1: Dev Review

#1313 Reorder setup the Mattermost Server bullet points
  site/content/contribute/developer-setup.md
Labels: 4: Reviews Complete, Contributor

#1314 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1315 Added easy link to sever/webapp component list
  site/content/contribute/more-info/server/plugins.md
  site/content/integrate/apps/_index.md
  site/content/integrate/getting-started/_index.md
  site/content/integrate/plugins/_index.md
  site/content/integrate/plugins/best-practices.md
  site/content/integrate/plugins/components/server/_index.md
  site/content/integrate/plugins/components/server/best-practices.md
  site/content/integrate/plugins/components/server/ha.md
  site/content/integrate/plugins/components/webapp/_index.md
  site/content/integrate/plugins/components/webapp/actions.md
  site/content/integrate/plugins/components/webapp/best-practices.md
  site/content/integrate/plugins/interactive-dialogs/_index.md
  site/content/integrate/plugins/interactive-messages/_index.md
  site/content/integrate/plugins/migration.md
  site/content/integrate/plugins/overview.md
  site/content/integrate/reference/_index.md
  site/content/integrate/reference/rest-api/_index.md
  site/content/integrate/reference/server/server-reference.md
  site/content/integrate/reference/webapp/webapp-reference.md
  site/content/integrate/slash-commands/_index.md
Labels: 4: Reviews Complete
