Repository mattermost/mattermost-developer-documentation, pull requests merged in 2023-07, with the labels that each got.

#1260 Update developer-setup.md
  site/content/contribute/developer-setup.md
Labels: 4: Reviews Complete

#1264 Typo fix
  site/content/contribute/more-info/server/_index.md
Labels: Contributor

#1266 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1277 manual cherry pick doc: suggest a remote branch name for the push
  site/content/contribute/more-info/getting-started/branching.md
Labels: 1: Dev Review

#1263 Adding instructions for enabling plugin uploads in Mattermost Omnibus installation
  site/content/integrate/plugins/using-and-managing-plugins.md
Labels: 4: Reviews Complete, Contributor

#1265 update autogenerated code and links for monorepo
  NOTICE.txt
  cmd/plugin-godocs/plugin-godocs.go
  cmd/plugin-manifest-docs/plugin-manifest-docs.go
  go.mod
  go.sum
  scripts/package-lock.json
  scripts/plugin-jsdocs.js
  site/content/contribute/expectations/_index.md
  site/content/contribute/more-info/getting-started/using-gitpod.md
  site/content/contribute/more-info/server/cli-commands.md
  site/content/contribute/more-info/server/plugins.md
  site/content/contribute/more-info/server/rest-api.md
  site/content/contribute/more-info/server/schema-migration-guide.md
  site/content/contribute/more-info/server/style-guide.md
  site/content/contribute/more-info/server/system_console.md
  site/content/contribute/more-info/webapp/e2e-cheatsheets.md
  site/content/contribute/more-info/webapp/e2e-testing.md
  site/content/contribute/more-info/webapp/migrating-to-typescript.md
  site/content/contribute/more-info/webapp/unit-testing.md
  site/content/integrate/apps/drivers/golang.md
  site/content/integrate/apps/functionality/mattermost-api.md
  site/content/integrate/apps/structure/call-metadata/_index.md
  site/content/integrate/apps/structure/call/_index.md
  site/content/integrate/customization/customization/server-files.md
  site/content/integrate/customization/customization/webapp.md
  site/content/integrate/plugins/components/server/hello-world.md
  site/content/integrate/plugins/components/server/reference.md
  site/content/integrate/plugins/components/webapp/reference.md
  site/content/integrate/plugins/developer-workflow.md
  site/content/integrate/plugins/example-plugins.md
  site/content/integrate/plugins/interactive-messages/_index.md
  site/content/integrate/plugins/migration.md
  site/content/integrate/plugins/overview.md
Labels: 4: Reviews Complete

#1279 Update API documentation steps
  site/content/contribute/more-info/server/rest-api.md
Labels: 4: Reviews Complete
