Repository mattermost/mattermost-developer-documentation, pull requests merged in 2023-08, with the labels that each got.

#1283 Added instruction to install rosetta on ARM macs for libpng to work
  site/content/contribute/developer-setup.md
Labels: 4: Reviews Complete

#1256 Fix broken links
  site/content/blog/2017-09-04-repo-split.md
  site/content/blog/2018-06-25-subpath.md
  site/content/blog/2018-10-18-idiomatic-error-handling.md
  site/content/blog/2019-06-04-percona-live-2019.md
  site/content/blog/2019-09-29-avoiding-flaky-tests.md
  site/content/blog/2019-10-21-localizing-matterpoll/index.md
  site/content/blog/2019-11-04-unit-testing-mmctl-commands.md
  site/content/blog/2020-01-13-incorporating-golangci-lint.md
  site/content/blog/2020-03-27-advanced-git-tbilisi-free-university.md
  site/content/blog/2020-05-04-pritunl.md
  site/content/blog/2020-06-10-opentracing.md
  site/content/blog/2020-07-27-automated-ui-testing-with-cypress.md
  site/content/blog/2020-11-17-mysql-index-merge.md
  site/content/blog/2021-02-02-streamlining-developer-access-to-prometheus-and-grafana.md
  site/content/blog/2021-06-01-migrating-operator-custom-resource.md
  site/content/contribute/expectations/_index.md
  site/content/contribute/more-info/containers/_index.md
  site/content/contribute/more-info/focalboard/personal-server-setup-guide.md
  site/content/contribute/more-info/getting-started/contribution-checklist.md
  site/content/contribute/more-info/server/developer-workflow.md
  site/content/contribute/more-info/server/feature-flags.md
  site/content/contribute/more-info/server/rest-api.md
  site/content/contribute/more-info/webapp/_index.md
  site/content/contribute/more-info/webapp/build-component.md
  site/content/contribute/more-info/webapp/e2e-testing.md
  site/content/integrate/customization/customization/webapp.md
  site/content/integrate/plugins/components/webapp/hello-world.md
  site/content/integrate/plugins/components/webapp/reference.md
  site/content/integrate/plugins/overview.md
  site/content/integrate/zapier-integration/_index.md
Labels: 4: Reviews Complete

#1285 Clarify which Apps can be deployed on MM Cloud
  site/content/integrate/apps/deploy/deploy-aws/_index.md
Labels: 1: Dev Review

#1286 Update _index.md
  site/content/contribute/more-info/focalboard/_index.md
Labels: 4: Reviews Complete

#1287 Correct max post size on slash command page
  site/content/integrate/slash-commands/_index.md
Labels: 4: Reviews Complete, Contributor

#1288 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1289 Archive legacy file: contributor wall of fame
  site/content/contribute/more-info/team_contributions/_index.md
Labels: 4: Reviews Complete
