Repository mattermost/mattermost-developer-documentation, pull requests merged in 2023-05, with the labels that each got.

#1240 Added min server requirements for app framework
  site/content/integrate/apps/_index.md
Labels: 4: Reviews Complete

#1248 [MM-52303] Desktop development docs update
  site/content/contribute/more-info/desktop/architecture/configuration.md
  site/content/contribute/more-info/desktop/architecture/external-views.md
  site/content/contribute/more-info/desktop/architecture/internal-views.md
  site/content/contribute/more-info/desktop/architecture/internal-views/calls-widget.png
  site/content/contribute/more-info/desktop/architecture/internal-views/loading-screen.png
  site/content/contribute/more-info/desktop/architecture/internal-views/main-window.png
  site/content/contribute/more-info/desktop/architecture/internal-views/settings-window.png
  site/content/contribute/more-info/desktop/architecture/logging.md
  site/content/contribute/more-info/desktop/architecture/navigation.md
Labels: 1: Dev Review

#1251 Update developer-workflow.md
  site/content/contribute/more-info/webapp/developer-workflow.md
Labels: 4: Reviews Complete, Contributor

#1247 MM-52754: Publish new schema migration guidelines
  site/content/contribute/more-info/server/ESR-diagram.png
  site/content/contribute/more-info/server/migrations_pie.png
  site/content/contribute/more-info/server/schema-migration-guide.md
  site/layouts/shortcodes/table.html
  site/static/css/styles.css
Labels: 2: Editor Review
