Repository mattermost/mattermost-developer-documentation, pull requests merged in 2023-10, with the labels that each got.

#1295 Update push proxy documentation for Android
  site/content/contribute/more-info/mobile/push-notifications/service.md
  site/static/img/mobile/firebase_cloud_messaging.png
  site/static/img/mobile/firebase_server_key.png
Labels: 4: Reviews Complete

#1297 Update the notification banner for Hacktoberfest
  site/config.toml
Labels: 2: Editor Review

#1293 Avoid running untrusted code as root to install nodejs
  site/content/contribute/more-info/desktop/developer-setup/ubuntu.md
Labels: 4: Reviews Complete, Contributor

#1296 Update plugins development to include dev setup links
  site/content/integrate/plugins/_index.md
Labels: 4: Reviews Complete

#1299 Update 404.html
  site/layouts/404.html
  site/layouts/partials/head-meta.html
  site/layouts/partials/head.html
  site/static/css/styles.css
Labels: 4: Reviews Complete

#1305 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1301 [MM-54869] Add nvm as the default NodeJS provider for the Desktop App
  site/content/contribute/more-info/desktop/developer-setup/arch.md
  site/content/contribute/more-info/desktop/developer-setup/redhat.md
  site/content/contribute/more-info/desktop/developer-setup/ubuntu.md
Labels: 4: Reviews Complete

#1307 Remove app deployment guides from developer docs
  site/content/integrate/apps/authentication/mattermost-to-app/_index.md
  site/content/integrate/apps/deploy/_index.md
  site/content/integrate/apps/deploy/deploy-aws/_index.md
  site/content/integrate/apps/deploy/deploy-aws/deploy-mm-aws.png
  site/content/integrate/apps/deploy/deploy-aws/deploy-third-party-aws.png
  site/content/integrate/apps/deploy/deploy-http/_index.md
  site/content/integrate/apps/deploy/deploy-openfaas/_index.md
  site/content/integrate/apps/deploy/package-for-aws.md
  site/content/integrate/apps/deploy/settings/_index.md
  site/content/integrate/apps/functionality/debug.md
  site/content/integrate/apps/quickstart/quick-start-serverless/_index.md
Labels: 4: Reviews Complete, Hacktoberfest, Contributor
