Repository mattermost/mattermost-developer-documentation, pull requests merged in 2023-01, with the labels that each got.

#1192 Update Hugo version to 0.101.0 for production builds
  .gitlab-ci.yml
Labels: 2: Editor Review, Contributor

#1164 Add site search capability
  .htmlvalidateignore
  site/config.toml
  site/content/contribute/expectations/_index.md
  site/content/contribute/good-decisions/_index.md
  site/content/contribute/more-info/_index.md
  site/content/contribute/why-contribute/_index.md
  site/content/integrate/apps/_index.md
  site/content/integrate/plugins/_index.md
  site/content/integrate/slash-commands/_index.md
  site/content/integrate/webhooks/_index.md
  site/content/search/_index.md
  site/content/search/searchindex.md
  site/layouts/_default/search.html
  site/layouts/_default/searchindex.json
  site/layouts/index.html
  site/layouts/partials/footer.html
  site/layouts/partials/hero.html
  site/layouts/partials/sidebar-v2.html
  site/static/css/styles.css
  site/static/js/main.js
  site/static/js/search-page.js
  site/static/js/search.js
Labels: 4: Reviews Complete, Contributor

#1198 Updated dev docs banner for Feb 16 webinar
  site/config.toml
Labels: 1: Dev Review, 2: Editor Review

#1191 Fix GitHub Casing
  site/content/contribute/expectations/_index.md
  site/content/contribute/more-info/mobile/build-your-own/_index.md
  site/layouts/partials/footer.html
Labels: 4: Reviews Complete, preview-environment, Contributor

#1202 Mobile style updates
  site/static/css/bar.css
  site/static/css/styles.css
Labels: 4: Reviews Complete

#1206 [MM-50056] Require DisplayName in app manifest
  site/content/integrate/apps/structure/manifest/_index.md
Labels: 4: Reviews Complete

#1208 Update _index.md
  site/content/contribute/more-info/mobile/build-your-own/_index.md
Labels: 4: Reviews Complete, Contributor

#1204 Fix for sidebar search input styles
  site/static/css/styles.css
Labels: 4: Reviews Complete

#1182 Document Apps #359: Ability to force refresh bindings for app after call
  site/content/integrate/apps/structure/bindings/_index.md
  site/content/integrate/apps/structure/call/_index.md
Labels: 4: Reviews Complete, Contributor

#1181 Document MM-48538: `/apps debug logs` to stream plugin logs to a Mattermost channel
  site/content/integrate/apps/functionality/_index.md
  site/content/integrate/apps/functionality/debug.md
Labels: 4: Reviews Complete, Contributor
