Repository mattermost/mattermost-developer-documentation, pull requests merged in 2024-01, with the labels that each got.

#1326 Remove Google Summer of Code page
  site/content/contribute/more-info/gsoc/_index.md
Labels: 4: Reviews Complete

#1327 Copyright update to 2024
  site/layouts/partials/footer.html
Labels: 4: Reviews Complete

#1328 Update style guide to reflect standard Go module layout
  site/content/contribute/more-info/server/style-guide.md
Labels: 4: Reviews Complete

#1324 [GH-1309] Correct Attachments documentation
  site/content/integrate/reference/message-attachments/_index.md
Labels: 4: Reviews Complete, preview-environment, Contributor

#1325 [MM-55746] Add documentation on how to use new `ServeMetrics` plugin hook
  site/content/integrate/plugins/best-practices.md
Labels: 4: Reviews Complete

#1323 Plugin requests can include Authorization headers from external systems
  site/content/integrate/plugins/components/server/best-practices.md
Labels: 4: Reviews Complete

#1332 [GH-1281] OpenSSL Compatibility: Add -legacy option
  site/content/contribute/more-info/mobile/push-notifications/service.md
Labels: 4: Reviews Complete, Contributor

#1329 Ticket Assignment Update Note
  site/content/contribute/more-info/getting-started/contribution-checklist.md
Labels: 4: Reviews Complete, Contributor
