Repository mattermost/mattermost-developer-documentation, pull requests merged in 2024-06, with the labels that each got.

#1375 Remove excess `<br>`
  site/content/contribute/more-info/mobile/build-your-own/android.md
  site/content/contribute/more-info/mobile/build-your-own/ios.md
Labels: 4: Reviews Complete, Contributor

#1376 Update documentation link for mobile app builds CI
  site/content/contribute/more-info/mobile/build-your-own/_index.md
Labels: 4: Reviews Complete, Contributor

#1380 GH-1378
  site/content/contribute/developer-setup/_index.md
Labels: 4: Reviews Complete, Contributor

#1384 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1377 Add Message Priority documentation
  site/content/integrate/reference/message-priority/_index.md
  site/content/integrate/reference/message-priority/message-priority-requested-ack.jpg
  site/content/integrate/reference/message-priority/message-priority-urgent.jpg
  site/content/integrate/webhooks/incoming/_index.md
  site/content/integrate/webhooks/outgoing/_index.md
Labels: 4: Reviews Complete

#1381 Update pluginapi cluster link to correct location
  site/content/integrate/plugins/components/server/ha.md
Labels: 4: Reviews Complete

#1385 Update notification bar with Copilot webinar CTA
  site/config.toml
Labels: 2: Editor Review, preview-environment

#1361 Update Bootstrap from 4.0.0-beta.2 to 4.6.2
  site/static/css/bootstrap.min.css
Labels: 4: Reviews Complete, Contributor
