Repository mattermost/mattermost-developer-documentation, pull requests merged in 2024-03, with the labels that each got.

#1345 feat: Migrate Production site to Github Actions
  .github/workflows/build.yml
  .github/workflows/cd.yml
  .gitlab-ci.yml
Labels: 1: Dev Review, 2: Editor Review

#1341 Remove maximum limit for elements in interactive dialogs
  site/content/integrate/plugins/interactive-dialogs/_index.md
Labels: 4: Reviews Complete, Contributor

#1348 Update _index.md fix list of fields of select element
  site/content/integrate/plugins/interactive-dialogs/_index.md
Labels: 4: Reviews Complete, Contributor

#1350 Add graddle lockfile update to the documentation
  site/content/contribute/more-info/mobile/build-your-own/android.md
Labels: 4: Reviews Complete

#1349 Adjust documentation around feature flags to remove references to split.io
  site/content/contribute/more-info/server/feature-flags.md
Labels: 4: Reviews Complete

#1351 Update developer-setup.md to provide no-docker setup
  site/content/contribute/developer-setup.md
Labels: 4: Reviews Complete, preview-environment, Contributor
