Repository mattermost/mattermost-developer-documentation, pull requests merged in 2024-07, with the labels that each got.

#1387 Update mobile dev setup to reflect requiring ruby 3.0.6
  site/content/contribute/more-info/mobile/developer-setup/_index.md
Labels: 1: Dev Review, 2: Editor Review

#1382 GH-1379 (Add `docs` directory to `.gitignore`)
  .gitignore
Labels: 4: Reviews Complete, Contributor

#1386 Fix indents in "Set up your development environment"
  site/content/contribute/developer-setup/_index.md
Labels: 4: Reviews Complete, Contributor

#1393 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1391 Replaces node-fetch v2 (sync-fetch) with node-fetch v3
  scripts/package-lock.json
  scripts/package.json
  scripts/plugin-jsdocs.js
Labels: 4: Reviews Complete, Contributor

#1389 How to enable SSL pinning on mobile
  site/content/contribute/more-info/mobile/build-your-own/ssl-pinning.md
Labels: 4: Reviews Complete

#1394 Update links to Go's 'Code Review Comments'
  site/content/contribute/more-info/server/style-guide.md
Labels: 4: Reviews Complete, Contributor

#1370 Update docs for debugging server plugins
  site/content/integrate/plugins/developer-workflow.md
Labels: 4: Reviews Complete
