Repository mattermost/mattermost-developer-documentation, pull requests merged in 2025-04, with the labels that each got.

#1443 Update github.com/mattermost/mattermost/server/public for latest plugin updates
  go.mod
  go.sum
Labels: 4: Reviews Complete

#1441 Update _index.md
  site/content/contribute/why-contribute/_index.md
Labels: 2: Editor Review, Contributor

#1444 Update MVP
  site/content/contribute/more-info/mvp/_index.md
Labels: 4: Reviews Complete

#1442 Move OpenAPI under developers website & add 2nd navigation bar.
  .htmlvalidateignore
  site/config.toml
  site/content/api-documentation/_index.md
  site/layouts/_default/api-documentation.html
  site/layouts/partials/head.html
  site/layouts/partials/intro.html
  site/layouts/partials/nav.html
  site/layouts/partials/nav2.html
  site/layouts/shortcodes/elements-api.html
  site/static/css/api-reference.css
  site/static/css/elements-custom.css
  site/static/css/second-nav.css
  site/static/css/styles.css
  site/static/img/home/apidocs.png
Labels: 1: PM Review, 4: Reviews Complete, 2: Editor Review

#1446 Update e2e-cheatsheets.md
  site/content/contribute/more-info/webapp/e2e-cheatsheets.md
Labels: 4: Reviews Complete, Contributor
